### ISSUE TITLE
Serialize an Array of strings

### ISSUE THREAD

**Issue by blanchma** [rails-api/active_model_serializers#1148]
I want to return an array of strings (for a search) and I get 

NoMethodError (undefined method `new' for nil:NilClass)

Can I disable AMS for a specific controller/action ?

**Comment by NullVoxPopuli** [comment]
can you provide a code example of what you are trying to do?

**Comment by blanchma** [comment]
@NullVoxPopuli look that I made a mistake in the description. I mean "array", not "hash"

class Api::GamesController < ApplicationController
  respond_to :json

  def index
    games = Meeting.select(:game).distinct.where("game LIKE ?", "%#{params[:game]}%").pluck(:game)
    render json: games
  end
end

**Comment by NullVoxPopuli** [comment]
what happens if you try the master branch of AMS?

**Comment by blanchma** [comment]
I'm using gem 'active_model_serializers', '0.10.0.rc2' (I need this version)

2015-09-14 13:05 GMT-03:00 L. Preston Sego III <notifications@github.com>:

**Comment by NullVoxPopuli** [comment]
rc3 is going to be released soon, but in the mean time, I *think* that this issue is resolved on master.

so,

`gem 'active_model_serializers', github: 'rails-api/active_model_serializers'`

should do the trick

**Comment by beauby** [comment]
@blanchma Could you confirm this worked for you?

**Comment by blanchma** [comment]
@beauby sorry for the delay. Yes, it works.

**Comment by beauby** [comment]
Cool, then I'm closing this for now. Feel free to reopen if the problem arises again in the future.

**Comment by pynixwang** [comment]
this happen again.
```
No serializer found for resource: "好色"
caught error of type UncaughtThrowError in after callback inside Grape::Middleware::Formatter : uncaught throw :no_serializer
  
UncaughtThrowError (uncaught throw :no_serializer):
  
active_model_serializers (0.10.6) lib/active_model/serializer/collection_serializer.rb:80:in `throw'
active_model_serializers (0.10.6) lib/active_model/serializer/collection_serializer.rb:80:in `serializer_from_resource'
active_model_serializers (0.10.6) lib/active_model/serializer/collection_serializer.rb:69:in `block in serializers_from_resources'
active_model_serializers (0.10.6) lib/active_model/serializer/collection_serializer.rb:68:in `map'
active_model_serializers (0.10.6) lib/active_model/serializer/collection_serializer.rb:68:in `serializers_from_resources'
active_model_serializers (0.10.6) lib/active_model/serializer/collection_serializer.rb:13:in `initialize'
grape-active_model_serializers (1.5.1) lib/grape-active_model_serializers/serializer_resolver.rb:10:in `new'
grape-active_model_serializers (1.5.1) lib/grape-active_model_serializers/serializer_resolver.rb:10:in `serializer'
grape-active_model_serializers (1.5.1) lib/grape-active_model_serializers/formatter.rb:27:in `fetch_serializer'
grape-active_model_serializers (1.5.1) lib/grape-active_model_serializers/formatter.rb:7:in `call'
grape (1.0.0) lib/grape/middleware/formatter.rb:44:in `block in build_formatted_response'
grape (1.0.0) lib/grape/middleware/formatter.rb:44:in `collect'
grape (1.0.0) lib/grape/middleware/formatter.rb:44:in `build_formatted_response'
grape (1.0.0) lib/grape/middleware/formatter.rb:28:in `after'
grape (1.0.0) lib/grape/middleware/base.rb:34:in `call!'
grape (1.0.0) lib/grape/middleware/base.rb:24:in `call'
grape (1.0.0) lib/grape/middleware/base.rb:31:in `call!'
grape (1.0.0) lib/grape/middleware/base.rb:24:in `call'
grape (1.0.0) lib/grape/middleware/error.rb:34:in `block in call!'
grape (1.0.0) lib/grape/middleware/error.rb:33:in `catch'
grape (1.0.0) lib/grape/middleware/error.rb:33:in `call!'
grape (1.0.0) lib/grape/middleware/base.rb:24:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
grape (1.0.0) lib/grape/endpoint.rb:227:in `call!'
grape (1.0.0) lib/grape/endpoint.rb:221:in `call'
grape (1.0.0) lib/grape/router/route.rb:72:in `exec'
grape (1.0.0) lib/grape/router.rb:119:in `process_route'
grape (1.0.0) lib/grape/router.rb:74:in `block in identity'
grape (1.0.0) lib/grape/router.rb:93:in `transaction'
grape (1.0.0) lib/grape/router.rb:72:in `identity'
grape (1.0.0) lib/grape/router.rb:57:in `block in call'
grape (1.0.0) lib/grape/router.rb:135:in `with_optimization'
grape (1.0.0) lib/grape/router.rb:56:in `call'
grape (1.0.0) lib/grape/api.rb:119:in `call'
grape (1.0.0) lib/grape/api.rb:45:in `call!'
grape (1.0.0) lib/grape/api.rb:40:in `call'
actionpack (5.0.2) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.0.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.2) lib/action_dispatch/routing/route_set.rb:725:in `call'

```

**Comment by pynixwang** [comment]
not gape problem
```
[18] pry(main)> ActiveModel::Serializer::CollectionSerializer.new(["xxx"])
No serializer found for resource: "xxx"
UncaughtThrowError: uncaught throw :no_serializer
```
