### ISSUE TITLE
What is the inline usage in 0.10?

### ISSUE THREAD

**Issue by youroff** [rails-api/active_model_serializers#1192]
With 0.9 I was able to do just `SomeSerializer.new(obj).to_json`. How to achieve something similar with the latest version?

**Comment by NullVoxPopuli** [comment]
```ruby
SerializableResource.new(obj).serializable_hash.to_json
```
(I believe)

**Comment by youroff** [comment]
Yeah, just found it in docs for master branch (it wasn't in 0.10-stable), but it didn't work either for some reason. Here's the trace:
```
NoMethodError: undefined method `new' for nil:NilClass
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc3/lib/active_model/serializable_resource.rb:34:in `serializer_instance'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc3/lib/active_model/serializable_resource.rb:29:in `adapter'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/active_model_serializers-0.10.0.rc3/lib/active_model/serializable_resource.rb:14:in `serializable_hash'
	from (irb):23
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/youroff/Documents/projects/autocloud/bin/rails:8:in `<top (required)>'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/youroff/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/youroff/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/youroff/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.2.1 :024 > r = ActiveModel::SerializableResource.new(u).serializable_hash

```

But now at least I see where to dig, thanks ;)

**Comment by beauby** [comment]
@youroff Seems like the inferred serializer for your resource does not exist.
