### ISSUE TITLE
undefined method `_cache' for NilClass:Class in cached_serializer.rb:23:in `cached?'

### ISSUE THREAD

**Issue by NullVoxPopuli** [rails-api/active_model_serializers#1461]
This happens when rendering a namespaced model from the controller.
Using `master`'s code as of the time of writing this issue (`8981683b9fa8d0bcff0e76b3702d699689b787b4`). (though, this happened with `efe5128a2e6b8578d81bc7a807ace427c0b4d847` as well.

```ruby
  def show
    model = operation_class.new(current_user, params, show_params).run
    ap model
    ap params
    # errors on the following line:
    render json: model, include: params[:include], serializer: RaffleTicketSerializer
  end
```

in the log of my test, it shows:

```
#<LineItem::RaffleTicket:0x0000000dae6340> {
     lots of attributes
}
{
     "raffle_id" => "1",
            "id" => "1",
    "controller" => "api/raffle_tickets",
        "action" => "show"
}
                                                                                                                                            
  1) Api::RaffleTicketsController show renders with the raffle ticket serializer
     Failure/Error: get :show, id: @ticket_option.id, raffle_id: @raffle.id
     NoMethodError:
       undefined method `_cache' for NilClass:Class
     # /home/me/.rvm/gems/ruby-2.3.0/gems/attr_encrypted-1.3.3/lib/attr_encrypted.rb:258:in `method_missing'
     # /home/me/.rvm/gems/ruby-2.3.0/bundler/gems/active_model_serializers-8981683b9fa8/lib/active_model/serializer/adapter/cached_serializer.rb:23:in `cached?'

```

I'm gonna see if I can replicate this in a branch.

**Comment by NullVoxPopuli** [comment]
I haven't gotten anywhere, but I found a more specific area where the error is happening:
```
From: /home/me/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.3/lib/action_controller/metal/renderers.rb @ line 116 ActionController::Renderers#_render_with_renderer_json:

    115: add :json do |json, options|
 => 116:   json = json.to_json(options) unless json.kind_of?(String)
```

json.to_json throws the error.

json is an ActiveModel::SerializableResource

**Comment by NullVoxPopuli** [comment]
the last line from AMS is in serialization.rb at:

```ruby
        super(serializable_resource, options)
```

at the bottom of the file

**Comment by NullVoxPopuli** [comment]
gonna close this, as it appears to have been an issue with my test

```ruby
expect(RaffleTicketSerializer).to receive(:new)
```
