### ISSUE TITLE
Namespacing serializers as namespaced models gives undefined method `all'

### ISSUE THREAD

**Issue by olegantonyan** [rails-api/active_model_serializers#1463]
0.9.4, rails 4.2.5, ruby 2.3.0, linux

I have 2 models
```ruby
# app/models/device.rb
class Device < ActiveRecord::Base
  has_one :status, class_name: 'Device::Status'
end

# app/models/device/status.rb
class Device::Status < ActiveRecord::Base
  belongs_to :device
end
```
And I want to put their serializers accordingly:
``` ruby
# serializers/api/v1/device_serializer.rb
class Api::V1::DeviceSerializer < Api::V1::BaseSerializer
  has_one :status # serializer: Api::V1::Device::StatusSerializer doesn't change anything
end

# serializers/api/v1/device/status_serializer.rb
class Api::V1::Device::StatusSerializer < Api::V1::BaseSerializer
end
```
But this causes error
```
NoMethodError (undefined method `all' for Api::V1::Device:Module)
```
I found discussions/prs about namespacing (#1196, #879), but none of them related to this particular case.

**Comment by beauby** [comment]
Could you provide a full stacktrace?

**Comment by olegantonyan** [comment]
Stacktrace:
```
[ 0] "/home/oleg/projects/rmpd_server/app/controllers/api/v1/devices_controller.rb:3:in `index'",
[ 1] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_controller/metal/implicit_render.rb:4:in `send_action'",
[ 2] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/abstract_controller/base.rb:198:in `process_action'",
[ 3] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_controller/metal/rendering.rb:10:in `process_action'",
[ 4] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'",
[ 5] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'",
[ 6] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'",
[ 7] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'",
[ 8] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'",
[ 9] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'",
[10] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'",
[11] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/abstract_controller/callbacks.rb:19:in `process_action'",
[12] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_controller/metal/rescue.rb:29:in `process_action'",
[13] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'",
[14] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `block in instrument'",
[15] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'",
[16] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:164:in `instrument'",
[17] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'",
[18] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'",
[19] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/railties/controller_runtime.rb:18:in `process_action'",
[20] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/abstract_controller/base.rb:137:in `process'",
[21] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionview-4.2.5/lib/action_view/rendering.rb:30:in `process'",
[22] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_controller/metal.rb:196:in `dispatch'",
[23] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'",
[24] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_controller/metal.rb:237:in `block in action'",
[25] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'",
[26] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:45:in `serve'",
[27] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:43:in `block in serve'",
[28] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `each'",
[29] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/journey/router.rb:30:in `serve'",
[30] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:817:in `call'",
[31] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-pjax-0.8.0/lib/rack/pjax.rb:12:in `call'",
[32] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/exception_notification-4.1.4/lib/exception_notification/rack.rb:32:in `call'",
[33] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/bullet-5.0.0/lib/bullet/rack.rb:12:in `call'",
[34] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/warden-1.2.4/lib/warden/manager.rb:35:in `block in call'",
[35] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/warden-1.2.4/lib/warden/manager.rb:34:in `catch'",
[36] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/warden-1.2.4/lib/warden/manager.rb:34:in `call'",
[37] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'",
[38] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'",
[39] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'",
[40] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/remotipart-1.2.1/lib/remotipart/middleware.rb:27:in `call'",
[41] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/params_parser.rb:27:in `call'",
[42] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/flash.rb:260:in `call'",
[43] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'",
[44] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'",
[45] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/cookies.rb:560:in `call'",
[46] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/query_cache.rb:36:in `call'",
[47] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'",
[48] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activerecord-4.2.5/lib/active_record/migration.rb:377:in `call'",
[49] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'",
[50] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:88:in `__run_callbacks__'",
[51] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'",
[52] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:81:in `run_callbacks'",
[53] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/callbacks.rb:27:in `call'",
[54] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/reloader.rb:73:in `call'",
[55] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'",
[56] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/web-console-2.0.0/lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'",
[57] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/web-console-2.0.0/lib/action_dispatch/debug_exceptions.rb:13:in `call'",
[58] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'",
[59] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:38:in `call_app'",
[60] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `block in call'",
[61] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `block in tagged'",
[62] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:26:in `tagged'",
[63] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/tagged_logging.rb:68:in `tagged'",
[64] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/rack/logger.rb:20:in `call'",
[65] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/quiet_assets-1.1.0/lib/quiet_assets.rb:27:in `call_with_quiet_assets'",
[66] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/request_store-1.3.0/lib/request_store/middleware.rb:9:in `call'",
[67] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/request_id.rb:21:in `call'",
[68] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'",
[69] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'",
[70] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/activesupport-4.2.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'",
[71] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'",
[72] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/middleware/static.rb:116:in `call'",
[73] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'",
[74] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:518:in `call'",
[75] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/application.rb:165:in `call'",
[76] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'",
[77] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/puma-2.15.3/lib/puma/server.rb:541:in `handle_request'",
[78] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'",
[79] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'",
[80] "/home/oleg/.rbenv/versions/2.3.0/lib64/ruby/gems/2.3.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'"
```

And code looks like this
```ruby
class Api::V1::DevicesController < Api::V1::BaseController
  def index
    render json: Device.all
  rescue NoMethodError => e
    #<NoMethodError: undefined method `all' for Api::V1::Device:Module>
    # stacktrace from here
  end
end
```

**Comment by olegantonyan** [comment]
I found what's wrong. It's not AMS fault. `Device.all` in controller confuses model `Device` with module aka namespace for serializer `Api::V1::Device`. 

To workaround this I have to specify top-level namespace for model `::Device.all`. Ugly and may be confusing. Is there a better solution?

**Comment by bf4** [comment]
Thanks for sharing the solution! Closing as resolved.
