### ISSUE TITLE
undefined method in serializer

### ISSUE THREAD

**Issue by JWesorick** [rails-api/active_model_serializers#1513]
I'm getting a `NoMethodError` when I run all my specs together, however running any single controllers specs pass just fine. What's also weird is the missing method is in a serializer that is not being used in the current context. I'm using `active_model_serializers (0.10.0.rc4)`. Here are the relevant bits:

```ruby
class UserSerializer < ActiveModel::Serializer
  cache key: 'user', expires_in: 12.hour

  attributes :id, :email
  attributes :has_twitter

  def has_twitter
    object.identity?('twitter')
  end
end

class UserPublicSerializer < ActiveModel::Serializer
  cache key: 'user_public', expires_in: 12.hour

  attributes :id, :first_name, :last_name

  def first_name
    object.first_name
  end

  def last_name
    object.last_initial
  end
end

module API
  module V1
    class PartnersController < APIController
      def mayor
        @partner = Partner.find(params[:partner_id])
        @mayor = @partner.competing_users.first
        if @mayor.present?
          render json: @mayor, serializer: UserPublicSerializer
        else
          render json: {}
        end
      end
  end
end
```

```
Failure/Error: get :mayor, partner_id: @partner.id
     NoMethodError:
       undefined method `has_twitter' for #<User:0x007fd2456b9aa8>
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activemodel-4.2.4/lib/active_model/attribute_methods.rb:433:in `method_missing'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/rolify-4.0.0/lib/rolify/role.rb:78:in `method_missing'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/acts_as_follower-0.2.1/lib/acts_as_follower/follower.rb:96:in `method_missing'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer.rb:127:in `read_attribute_for_serialization'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer.rb:125:in `read_attribute_for_serialization'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/field.rb:17:in `value'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/attributes.rb:22:in `block in attributes'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/attributes.rb:19:in `each'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/attributes.rb:19:in `each_with_object'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/attributes.rb:19:in `attributes'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/attributes.rb:60:in `block in resource_object_for'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/base.rb:33:in `block in cache_check'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/cached_serializer.rb:18:in `cache_check'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/base.rb:32:in `cache_check'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/attributes.rb:59:in `resource_object_for'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/attributes.rb:31:in `serializable_hash_for_single_resource'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/attributes.rb:16:in `serializable_hash'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/fragment_cache.rb:31:in `fetch'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/cached_serializer.rb:16:in `cache_check'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/base.rb:32:in `cache_check'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/attributes.rb:59:in `resource_object_for'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/attributes.rb:31:in `serializable_hash_for_single_resource'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/attributes.rb:16:in `serializable_hash'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer/adapter/base.rb:22:in `as_json'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/json/encoding.rb:35:in `encode'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/json/encoding.rb:22:in `encode'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializable_resource.rb:7:in `to_json'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model_serializers/logging.rb:69:in `block (3 levels) in notify'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model_serializers/logging.rb:22:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model_serializers/logging.rb:22:in `block (3 levels) in instrument_rendering'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model_serializers/logging.rb:79:in `block in notify_render'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model_serializers/logging.rb:78:in `notify_render'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model_serializers/logging.rb:21:in `block (2 levels) in instrument_rendering'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model_serializers/logging.rb:92:in `block in tag_logger'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model_serializers/logging.rb:92:in `tag_logger'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model_serializers/logging.rb:20:in `block in instrument_rendering'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `instance_exec'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `block in make_lambda'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `block in simple'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_render_callbacks'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model_serializers/logging.rb:68:in `block (2 levels) in notify'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/renderers.rb:116:in `block in <module:Renderers>'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/action_controller/serialization.rb:61:in `block (2 levels) in <module:Serialization>'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/renderers.rb:45:in `block in _render_to_body_with_renderer'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/renderers.rb:41:in `_render_to_body_with_renderer'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/abstract_controller/rendering.rb:25:in `render'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:16:in `render'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/core_ext/benchmark.rb:12:in `ms'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:43:in `render'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/meta-tags-2.0.0/lib/meta_tags/controller_helper.rb:26:in `render_with_meta_tags'
     # ./app/controllers/api/v1/partners_controller.rb:77:in `mayor'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:198:in `process_action'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:137:in `process'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionview-4.2.4/lib/action_view/rendering.rb:30:in `process'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/test_case.rb:637:in `process'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/test_case.rb:65:in `process'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/devise-3.5.1/lib/devise/test_helpers.rb:19:in `block in process'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/devise-3.5.1/lib/devise/test_helpers.rb:72:in `catch'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/devise-3.5.1/lib/devise/test_helpers.rb:72:in `_catch_warden'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/devise-3.5.1/lib/devise/test_helpers.rb:19:in `process'
     # /Users/jakewesorick/.rvm/gems/ruby-2.2.3/gems/actionpack-4.2.4/lib/action_controller/test_case.rb:512:in `get'
     # ./spec/controllers/api/v1/partners_controller_spec.rb:221:in `block (3 levels) in <top (required)>'
```

**Comment by bf4** [comment]
Thanks for the bug report!  It's pretty easy to see where in `read_attribute_for_serialization` the error is coming from and that it's calling a method on the object that only exists on the serializer.  This may be related to or share a fix with https://github.com/rails-api/active_model_serializers/issues/1509


Awesome job sharing the stack trace

```ruby
    def read_attribute_for_serialization(attr)
      if self.class._serializer_instance_method_defined?(attr)
        send(attr)
      elsif self.class._fragmented
          # .rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer.rb:125:in 
        self.class._fragmented.read_attribute_for_serialization(attr)
      else
        # .rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.0.rc4/lib/active_model/serializer.rb:127:in 
        object.read_attribute_for_serialization(attr)
      end
    end
```

The problem is that

```ruby
      if self.class._serializer_instance_method_defined?(attr)
        send(attr)
```

should be calling `has_twitter` on the serializer, but `self.class._serializer_instance_method_defined?(attr)` is false for some reason (race condition, dynamic code, etc).

A hotfix would be to use the block form

```ruby
  attributes :has_twitter do
    object.identity?('twitter')
  end
```

or modify the read_attribute_for_serialization method... :(

**Comment by bf4** [comment]
I tagged it as a duplicate since the failure is in the same part of the code, even though it has a different etiology https://github.com/rails-api/active_model_serializers/issues/1509

**Comment by JWesorick** [comment]
I tried switching to the block form but I'm still seeing the issue. I'm kinda confused though, why is `read_attribute_for_serialization` even being called for `has_twitter` when it's not even in the serializer being used?

**Comment by bf4** [comment]
Maybe I was too quick to interpret the stacktrace. I'll take another look tomorrow, and maybe we can pair or chat in the slack.

B mobile phone

**Comment by JWesorick** [comment]
Is this the issue?

https://github.com/rails-api/active_model_serializers/blob/v0.10.0.rc4/lib/active_model/serializer/adapter/fragment_cache.rb#L21

`serializers = fragment_serializer(serializer.object.class.name, klass)`

This doesn't seem to be taking into account that I have 2 different serializers for the same object.

**Comment by bf4** [comment]
I wonder if that's fixed for you on master.

**Comment by JWesorick** [comment]
The same things seems to be happening with the latest from master.

**Comment by bf4** [comment]
could you provide a sample User class we can use to generate a failing test?

**Comment by JWesorick** [comment]
Yea, I think just any two serializers for the same object with different attributes and a cache will cause it. I'll try to make a basic app with the issue when I get a chance.

**Comment by JWesorick** [comment]
Here is an app that has the issue: https://github.com/JWesorick/active_model_serializers_bug
You can run the tests with `rake test test/controllers/welcome_controller_test.rb`

In this one, the public serializer is being used but is throwing an error `undefined method super_secret ` which is in the private serializer.

**Comment by groyoh** [comment]
@bf4 I wanted to try out the fragment cache and noticed the same behavior. So I started to write #1527 to tried to understand fragment cache a bit better.
@JWesorick is right when he says:
> I think just any two serializers for the same object with different attributes and a cache will cause it

By looking [here](https://github.com/rails-api/active_model_serializers/blob/f02f0849b1de9bd6dba0892aead1862064d29ce1/lib/active_model/serializer/adapter/fragment_cache.rb#L21) and [here](https://github.com/rails-api/active_model_serializers/blob/f02f0849b1de9bd6dba0892aead1862064d29ce1/lib/active_model/serializer/adapter/fragment_cache.rb#L86), you can see that the cached and non cached serializers will be created based on the model name. That means that two serializer using fragment cache and serializing the same model will work with the same cached and non cached serializers (e.g. `UserCachedSerializer` and `UserNonCachedSerializer`). Each serializer will add some attributes to the same cached and non cached serializers (see [here](https://github.com/rails-api/active_model_serializers/blob/f02f0849b1de9bd6dba0892aead1862064d29ce1/lib/active_model/serializer/adapter/fragment_cache.rb#L57)).

In the example given by @JWesorick (https://github.com/JWesorick/active_model_serializers_bug), here is what happens:
* The private [controller](https://github.com/JWesorick/active_model_serializers_bug/blob/master/test/controllers/welcome_controller_test.rb#L10) is called 
* The `User` is serialized with the [`UserPrivateSerializer`](https://github.com/JWesorick/active_model_serializers_bug/blob/master/app/serializers/user_private_serializer.rb) and the fragment cache is called:
  * a `UserCachedSerializer` and `UserNonCachedSerializer` are created
  * the attributes `:id`, `:name` are added to `UserCachedSerializer` and `:secret` to `UserNonCachedSerializer`
  * the `User` is serialized using `UserCachedSerializer` and `UserNonCachedSerializer`. The latter calls `object.read_attribute_for_serialization(:super_secret)` and delegate it to  `UserPrivateSerializer` which defines this method
  * the test pass
* The public [controller](https://github.com/JWesorick/active_model_serializers_bug/blob/master/test/controllers/welcome_controller_test.rb#L3)
* The `User` is serialized with the [`UserPublicSerializer`](https://github.com/JWesorick/active_model_serializers_bug/blob/master/app/serializers/user_public_serializer.rb) and the fragment cache is called:
  * `UserCachedSerializer` and `UserNonCachedSerializer` are already created
  * the attributes `:id`, `::email` are added to `UserCachedSerializer` and `:super_secret` to `UserNonCachedSerializer`
  * the `User` is serialized using `UserCachedSerializer` and `UserNonCachedSerializer`. The latter calls `object.read_attribute_for_serialization(:super_secret)` and delegate it to  `UserPublicSerializer` which does not define this method
  * the serialization fails
  * the test fail

I'm not sure if I was clear here. But the solution for me would be to build cache/non cached serializers based on the serializer's name and not on the model's name. I could try to provide a PR for this as it is blocking me as well.
