### ISSUE TITLE
Overriding serializer lookup when rendering

### ISSUE THREAD

**Issue by nicklandgrebe** [rails-api/active_model_serializers#1743]
#### Expected behavior vs actual behavior

Expected: I define `resource.serializer_class`, and this allows me to customize the serializer for a given class, and have that serializer be used as `:each_serializer` when serializing a collection of records of that class.

Actual: I define `resource.serializer_class`, and that serializer is used both when serializing a singular instance of that class, and when serializing a collection of records of that class.

This is because serializer look up preferentially returns `resource.serializer_class` (no matter if the resource is one record or a collection), then `config.collection_serializer` if the resource is a collection. 

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

I have a model and corresponding serializer. For example:

```
class AttributeValue < ActiveRecord::Base
  def serializer_class
    Api::V1::AttributeValueSerializer  
  end
end

module Api
  module V1
    class AttributeValueSerializer < ActiveModel::Serializer
    end
  end
end
```

Now, if I serialize `AttributeValue.find(5)`, or `AttributeValue.all`, we try to use `Api::V1::AttributeValueSerializer`, despite it not being a CollectionSerializer, so when serializing a collection this breaks with:

```
NoMethodError - undefined method `read_attribute_for_serialization' for #<ActiveRecord::Associations::CollectionProxy []>:
  activerecord (4.2.6) lib/active_record/relation/delegation.rb:136:in `method_missing'
  activerecord (4.2.6) lib/active_record/relation/delegation.rb:99:in `method_missing'
  active_model_serializers (0.10.0.rc5) lib/active_model/serializer.rb:182:in `read_attribute_for_serialization'
  active_model_serializers (0.10.0.rc5) lib/active_model_serializers/adapter/json_api/resource_identifier.rb:32:in `id_for'
  active_model_serializers (0.10.0.rc5) lib/active_model_serializers/adapter/json_api/resource_identifier.rb:7:in `initialize'
  active_model_serializers (0.10.0.rc5) lib/active_model_serializers/adapter/json_api/relationship.rb:46:in `data_for'
  active_model_serializers (0.10.0.rc5) lib/active_model_serializers/adapter/json_api/relationship.rb:14:in `initialize'
  active_model_serializers (0.10.0.rc5) lib/active_model_serializers/adapter/json_api.rb:432:in `block in relationships_for'
  active_model_serializers (0.10.0.rc5) lib/active_model/serializer/associations.rb:94:in `block (2 levels) in associations'
  active_model_serializers (0.10.0.rc5) lib/active_model/serializer/associations.rb:90:in `block in associations'
  active_model_serializers (0.10.0.rc5) lib/active_model_serializers/adapter/json_api.rb:430:in `relationships_for'
  active_model_serializers (0.10.0.rc5) lib/active_model_serializers/adapter/json_api.rb:300:in `resource_object_for'
  active_model_serializers (0.10.0.rc5) lib/active_model_serializers/adapter/json_api.rb:241:in `process_resource'
  active_model_serializers (0.10.0.rc5) lib/active_model_serializers/adapter/json_api.rb:231:in `block in resource_objects_for'
  active_model_serializers (0.10.0.rc5) lib/active_model_serializers/adapter/json_api.rb:231:in `resource_objects_for'
  active_model_serializers (0.10.0.rc5) lib/active_model_serializers/adapter/json_api.rb:74:in `success_document'
  active_model_serializers (0.10.0.rc5) lib/active_model_serializers/adapter/json_api.rb:49:in `serializable_hash'
  active_model_serializers (0.10.0.rc5) lib/active_model_serializers/adapter/base.rb:27:in `as_json'
```

I know that serializer look up is capable of using namespaces. I need to scope the serializers by a version namespace, but I cannot scope the models by a version namespace. Primarily because I don't want versioned models, but also because I define serializers both in `Api::V1::SomeSerializer` namespace, and the root namespace of just `SomeSerializer`. Some endpoints on my server will want to make use of the `Api::V1` namespace, others make use of the root namespace.

*Is there a way to contextually define serializer lookup using existing functionality? If not:*

I have to provide ASM with some way to determine where it should be looking up serializers given the specific context of the endpoint. I've come up with a solution somewhat based on `active_model/serializer/collection_serializer:14-16`:

```
def initialize(resources, options = {})
  ...
  serializer_context_class = options.fetch(:serializer_context_class, ActiveModel::Serializer)
  @serializers = resources.map do |resource|
    serializer_class = options.fetch(:serializer) { serializer_context_class.serializer_for(resource) }
  end
  ...
end
```

That is, to have an option that can be passed into `render`, called `:serializer_context_class`, that allows us to define what class we call `serializer_for` on when searching for a serializer in `active_model_serializers/serializable_resource:57`:

```
  def serializer
      @serializer ||=
        begin
          @serializer = serializer_opts.delete(:serializer)
          @serializer ||= ActiveModel::Serializer.serializer_for(resource)

          if serializer_opts.key?(:each_serializer)
            serializer_opts[:serializer] = serializer_opts.delete(:each_serializer)
          end
          @serializer
        end
    end
```

The appropriate change would then be:
```
def serializer
      @serializer ||=
        begin
          @serializer = serializer_opts.delete(:serializer)
          serializer_context_class = serializer_opts.delete(:serialization_context_class) || ActiveModel::Serializer
          @serializer ||= serializer_context_class.serializer_for(resource)

          if serializer_opts.key?(:each_serializer)
            serializer_opts[:serializer] = serializer_opts.delete(:each_serializer)
          end
          @serializer
        end
    end
```

And I could make use of it by doing something like this:
```
class AttributeValue < ActiveRecord::Base
end

module Api
  module V1
    class ApiSerializer < ActiveModel::Serializer
      def self.serializer_for(resource, options = {})
        "Api::V1::#{resource.class.name}".constantize
      end
    end

    class AttributeValueSerializer < ApiSerializer
    end
  end
end
```
```
module Api
  module V1
    class AttributeValuesController < ActionController::Base
      def show
        render json: AttributeValue.find(params[:id]), serialization_context_class: ApiSerializer
      end
    end
  end
end
```

*Note:* there are other instances where we use a serializer look up chain, and in those instances we use `serializer.class.serializer_for`, which technically accomplishes what I want (assuming `serializer.class.is_a?(ApiSerializer)`, but here, in the top level search for a serializer, I am limited to only what ActiveModel::Serializer is capable of finding in its standard definition. I want to override that so I can search however I want. Thoughts?

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: `0.10.0.rc5`

Output of `ruby -e "puts RUBY_DESCRIPTION"`: `ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]`

OS Type & Version: Mac OS X El Capitan 10.11.3

Integrated application and version *(e.g., Rails, Grape, etc)*: Rails 4.2.6

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

**Comment by nicklandgrebe** [comment]
I believe I can accomplish this by just using `:serializer` and doing the lookup myself before the render.
