### ISSUE TITLE
Possible regression in 0.10.1 - Object instance variable in parent serializer set to serializer in 10.1

### ISSUE THREAD

**Issue by theotherzach** [rails-api/active_model_serializers#1813]
#### Expected behavior vs actual behavior

This bug came up after I upgraded AMS from 0.10.0 to 0.10.1. Note that I cannot reproduce this behavior outside of the controller.

**Given**

* A serializer defines a custom method which makes a call to the `object` method
```ruby
def total_cents
  p object
  object.quantity * object.price_cents
end
```
* A second serializer inherits from the above serializer

**When**

* The second serializer is explicitly instantiated inside of a controller. 

**Result**

* The `object` call in `total_cents` defined on the parent serializer references a serializer

**Expected**

* The `object` call in `total_cents` should reference the object being serialized

#### Steps to reproduce

I believe that these are all of the relevant files and the Rspec test that exposes the error. Please let me know if this isn't detailed enough.

```ruby
# app/serializers/api/v1/order_line_item_serializer.rb
module Api::V1

  class OrderLineItemSerializer < ActiveModel::Serializer

    attributes :id,
               :order_id,
               :variant_id,
               :quantity,
               :price_cents,
               :total_cents,
               :created_at,
               :updated_at,

               def total_cents
                  p object
                 object.quantity * object.price_cents
               end

  end

end
```

```ruby
# app/serializers/api/v1/cart/order_line_item_serializer.rb
module Api::V1

  class Cart::OrderLineItemSerializer < Api::V1::OrderLineItemSerializer

    attributes :product_name, :variant_name

    def product_name
      object.variant.product_name
    end

    def variant_name
      object.variant.name
    end

  end

end
```

```ruby
module Api::V1
# app/controllers/api/v1/order_line_items_controller.rb

  class OrderLineItemsController < BaseController

    before_action :assign_and_authorize_order_line_item, only: [:update, :destroy]

    # PATCH /api/v1/order_line_items/:id
    def update
      if @order_line_item.update_attributes(order_line_item_params)
        render json: ::Api::V1::Cart::OrderLineItemSerializer.new(@order_line_item), status: :ok
      else
        render json: @order_line_item.errors.to_json, status: :unprocessable_entity
      end
    end

    # DELETE /api/v1/orders_line_items/:id
    def destroy
      if @order_line_item.destroy
        render json: ::Api::V1::Cart::OrderLineItemSerializer.new(@order_line_item), status: :ok
      else
        render json: @order_line_item.errors.to_json, status: :unprocessable_entity
      end
    end

    private

    def order_line_item_params
      params.permit(:quantity)
    end

    def assign_and_authorize_order_line_item
      @order_line_item = OrderLineItem.find(params.fetch(:id))
    end

  end

end
```

```ruby
# spec/controllers/api/v1/order_line_items_controller_spec.rb
require "rails_helper"

RSpec.describe Api::V1::OrderLineItemsController, type: :controller do
  let!(:order) { create(:order, :with_order_line_items) }
  let(:line_item) { order.order_line_items.first }

  before do
    @request.session[:cart_token] = order.cart_token
  end

  describe "#update" do
    context "happy path" do
      let(:valid_put) { put :update, id: line_item.id, quantity: 10 }

      it "updates the record" do
        expect { valid_put }.to change { line_item.reload.quantity }
      end
  end
end
```

*(e.g., detailed walkthrough, runnable script, example application)*

#### Environment

ActiveModelSerializers Version: 0.10.1, NOT 0.10.0

Output of `ruby -e "puts RUBY_DESCRIPTION"`: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

OS Type & Version: OSX 10.11.5 (15F34)

Integrated application and version *(e.g., Rails, Grape, etc)*: Rails 4.2.6

#### Backtrace
```
Run options: include {:focus=>true, :locations=>{"./spec/controllers/api/v1/order_line_items_controller_spec.rb"=>[16]}}

Randomized with seed 1796
#<Api::V1::Cart::OrderLineItemSerializer:0x007fb8e92a02e8 @object=#<OrderLineItem id: 1, order_id: 1, variant_id: 1, quantity: 10, price_cents: 6509, price_currency: "USD", created_at: "2016-06-17 20:12:59", updated_at: "2016-06-17 20:12:59", weight_ounces: #<BigDecimal:7fb8e9269608,'0.78E2',9(18)>>, @instance_options={}, @root=nil, @scope=nil, @serializer_class=Api::V1::Cart::OrderLineItemSerializer>
F

Failures:

  1) Api::V1::OrderLineItemsController#update happy path updates the record
     Failure/Error: object.quantity * object.price_cents

     NoMethodError:
       undefined method `quantity' for #<Api::V1::Cart::OrderLineItemSerializer:0x007fb8e92a02e8>
     # ./app/serializers/api/v1/order_line_item_serializer.rb:16:in `total_cents'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model/serializer.rb:196:in `read_attribute_for_serialization'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model/serializer/field.rb:23:in `value'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model/serializer/attributes.rb:22:in `block in attributes'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model/serializer/attributes.rb:19:in `each'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model/serializer/attributes.rb:19:in `each_with_object'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model/serializer/attributes.rb:19:in `attributes'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model/serializer/caching.rb:216:in `fetch_attributes'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model/serializer.rb:170:in `serializable_hash'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model_serializers/adapter/attributes.rb:7:in `serializable_hash'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model_serializers/adapter/base.rb:59:in `as_json'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model_serializers/serializable_resource.rb:8:in `to_json'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model_serializers/logging.rb:69:in `block (3 levels) in notify'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model_serializers/logging.rb:22:in `call'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model_serializers/logging.rb:22:in `block (3 levels) in instrument_rendering'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model_serializers/logging.rb:79:in `block in notify_render'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model_serializers/logging.rb:78:in `notify_render'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model_serializers/logging.rb:21:in `block (2 levels) in instrument_rendering'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model_serializers/logging.rb:95:in `block in tag_logger'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model_serializers/logging.rb:95:in `tag_logger'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model_serializers/logging.rb:20:in `block in instrument_rendering'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/active_model_serializers/logging.rb:68:in `block (2 levels) in notify'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/active_model_serializers-0.10.1/lib/action_controller/serialization.rb:52:in `block (2 levels) in <module:Serialization>'
     # ./app/controllers/api/v1/order_line_items_controller.rb:10:in `update'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/devise-3.5.9/lib/devise/test_helpers.rb:19:in `block in process'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/devise-3.5.9/lib/devise/test_helpers.rb:72:in `catch'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/devise-3.5.9/lib/devise/test_helpers.rb:72:in `_catch_warden'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/devise-3.5.9/lib/devise/test_helpers.rb:19:in `process'
     # /Users/zach/.rvm/gems/ruby-2.2.3/gems/gon-6.0.1/lib/gon/spec_helpers.rb:15:in `process'
     # ./spec/controllers/api/v1/order_line_items_controller_spec.rb:13:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/api/v1/order_line_items_controller_spec.rb:16:in `block (5 levels) in <top (required)>'
     # ./spec/controllers/api/v1/order_line_items_controller_spec.rb:16:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:87:in `block (2 levels) in <top (required)>'

Finished in 1.31 seconds (files took 9.08 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/controllers/api/v1/order_line_items_controller_spec.rb:15 # Api::V1::OrderLineItemsController#update happy path updates the record

Randomized with seed 1796



```

**Comment by theotherzach** [comment]
Here is the result of the same test run under 0.10.0

```
Run options: include {:focus=>true, :locations=>{"./spec/controllers/api/v1/order_line_items_controller_spec.rb"=>[16]}}

Randomized with seed 47014
#<OrderLineItem id: 1, order_id: 1, variant_id: 1, quantity: 10, price_cents: 1468, price_currency: "USD", created_at: "2016-06-17 20:15:59", updated_at: "2016-06-17 20:15:59", weight_ounces: #<BigDecimal:7fc5beabe150,'0.62E2',9(18)>>
.

Finished in 0.98551 seconds (files took 6.03 seconds to load)
1 example, 0 failures

Randomized with seed 47014

```

**Comment by bf4** [comment]
Hi @theotherzach !!!

So, My first response is that calling the serializer directly is more a something I'm trying to improve, than the official usage.  (re: improve, it wasn't long ago that it wasn't possible :)

So, since I'm just skimming the issue right now, and I imagine this is for work, have you tried using `render json: @order_line_item, status: :ok, serializer: ::Api::V1::Cart::OrderLineItemSerializer.new`  or `ActiveModelSerializers::SerializableResource` (if you want to go all manual)

Debug question:  Does `::Api::V1::OrderLineItemSerializer.new(@order_line_item).total_cents` return the same as ``::Api::V1::Cart::OrderLineItemSerializer.new(@order_line_item).total_cents`?

My hypothesis based on the stacktrace: 

- the Rails JSON renderer says `json = json.is_a?(String) ? json : json_to.json(options)`.
- AMS intercepts the render before it gets to that point and calls a bunch of methods to determine whether it has a serializer available for the render argument.
- Since you're neither passing in a `String/Hash/Array` nor an ActiveRecord, but rather a `::Api::V1::Cart::OrderLineItemSerializer` instance, it's trying to look up a serializer for *that* object.
- Try calling 'to_json' on it in your render statement `::Api::V1::Cart::OrderLineItemSerializer.new(@order_line_item).to_json`

You might find some helpful pointers on this in my (not yet merged :() pr in rails https://github.com/rails/rails/pull/21496/files#diff-2fcea0f1eade004d26946f92c9a9455eR251 or in http://www.benjaminfleischer.com/journey-of-a-media-type-in-rails-part-1 or maybe even http://www.benjaminfleischer.com/2015/06/02/understanding-rails-model-serializers/

**Comment by theotherzach** [comment]
### Using `serializer:`
>So, since I'm just skimming the issue right now, and I imagine this is for work, have you tried using render json: @order_line_item, status: :ok, serializer: ::Api::V1::Cart::OrderLineItemSerializer.new or ActiveModelSerializers::SerializableResource (if you want to go all manual)

I hadn't and that works!

```ruby
render json: @order_line_item, serializer: Api::V1::Cart::OrderLineItemSerializer, status: :ok
```

### Debug Answer
>Debug question: Does ::Api::V1::OrderLineItemSerializer.new(@order_line_item).total_cents return the same as `::Api::V1::Cart::OrderLineItemSerializer.new(@order_line_item).total_cents?

They appear to.:

The result of
```ruby
    def update
      p "fire one", ::Api::V1::OrderLineItemSerializer.new(@order_line_item).total_cents
      p "fire two", ::Api::V1::Cart::OrderLineItemSerializer.new(@order_line_item).total_cents
      if @order_line_item.update_attributes(order_line_item_params)
        render json: Api::V1::Cart::OrderLineItemSerializer.new(@order_line_item), status: :ok
      else
        render json: @order_line_item.errors.to_json, status: :unprocessable_entity
      end
    end
```

is

```
"fire one"
37428
"fire two"
37428
F

Failures:

  1) Api::V1::OrderLineItemsController#update happy path updates the record
     Failure/Error: object.quantity * object.price_cents

     NoMethodError:
       undefined method `quantity' for #<Api::V1::Cart::OrderLineItemSerializer:0x007f7f9f9c28b0>
```

### The `to_json` hypothesis

>Try calling 'to_json' on it in your render statement

Bingo, got it. This works:

```ruby
render json: Api::V1::Cart::OrderLineItemSerializer.new(@order_line_item).to_json, status: :ok
```

### How I Got Here

Thank you so much for the work you've done in allowing serializers to be called manually. I often start with an API first approach and then collapse portions back down into a big ball of bootstrappin' mud using the Gon gem like so:

```ruby
  def send_data_to_js
    gon.COUNTRIES = OrderAddress::COUNTRY_LIST
    gon.STATES = States.to_h
    gon.order = Api::V1::Cart::OrderSerializer.new(@order)

    if current_user.present?
      gon.current_user = Api::V1::UserSerializer.new(current_user)
      gon.user_addresses = ActiveModel::Serializer::CollectionSerializer
                           .new(current_user.user_addresses, serializer: Api::V1::UserAddressSerializer)
    else
      gon.current_user = {}
      gon.user_addresses = []
    end
end
```

That might be why I was assuming a more manual process than others might.

### Conclusion

The real issue is that I was assuming that `render` would coerce just about anything via `to_json` if available and I didn't realize that there was a lookup step involved. This might be such an edge case as to not warrant either a patch or a documentation update. In ideal world, should `render` blow up if it's given an AMS instance?

**Comment by bf4** [comment]
If you write the pr :)

B mobile phone

**Comment by theotherzach** [comment]
Would you mind pointing me in the general direction of the code that I would need to update? Nothing too specific, just a general hand-wave to the directory I should start in would be great.

**Comment by bf4** [comment]
could be somewhere in https://github.com/rails-api/active_model_serializers/blob/32a3b5389274054910e7485912169a55384cea68/lib/active_model_serializers/serializable_resource.rb

but probably just  https://github.com/rails-api/active_model_serializers/blob/32a3b5389274054910e7485912169a55384cea68/lib/action_controller/serialization.rb#L26-L28

```diff
    def get_serializer(resource, options = {})
+    return resource if resource.is_a?(ActiveModel::Serializer)
```

**Comment by bf4** [comment]
@theotherzach how are you feeling about making a PR?

**Comment by theotherzach** [comment]
Hey @bf4, sorry that I've been quiet on this. I'm still at least a week away from this PR, unfortunately. :( 

I'll put time on my calendar for this weekend.
