### ISSUE TITLE
Undefined method 'key?' -- NoMethodError

### ISSUE THREAD

**Issue by cannahum** [rails-api/active_model_serializers#1819]
#### Expected behavior vs actual behavior
I'm trying to run my Rails app on Heroku, but it fails at start because of the NoMethodError

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 0.10.1

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 

OS Type & Version: 

Integrated application and version *(e.g., Rails, Grape, etc)*: Rails 4.2.3

#### Backtrace
```
=> Booting WEBrick
=> Rails 4.2.3 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/app/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.10.1/lib/active_model/serializer/field.rb:76:in `condition_type': undefined method `key?' for :vote_options:Symbol (NoMethodError)
	from /app/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.10.1/lib/active_model/serializer/field.rb:47:in `validate_condition!'
	from /app/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.10.1/lib/active_model/serializer/field.rb:10:in `initialize'
	from /app/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.10.1/lib/active_model/serializer/reflection.rb:38:in `initialize'
	from /app/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.10.1/lib/active_model/serializer/associations.rb:43:in `new'
	from /app/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.10.1/lib/active_model/serializer/associations.rb:43:in `has_many'
	from /app/app/serializers/post_serializer.rb:3:in `<class:PostSerializer>'
	from /app/app/serializers/post_serializer.rb:1:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:317:in `depend_on'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:233:in `require_dependency'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:471:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:471:in `block in eager_load!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:469:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:469:in `eager_load!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:346:in `eager_load!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/finisher.rb:56:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /app/vendor/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
	from /app/config/environment.rb:5:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /app/config.ru:3:in `block in <main>'
	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /app/config.ru:in `new'
	from /app/config.ru:in `<main>'
	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/server.rb:61:in `app'
	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/server.rb:80:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /app/bin/rails:8:in `require'
	from /app/bin/rails:8:in `<main>'

```

#### Additonal helpful information
Here is the file that makes the problem:
```


class PostSerializer < ActiveModel::Serializer
  attributes :id, :caption, :anonymous, :active, :vote_type, :photo_count, :location, :updated_at, :aws_key, :user, :favorite
  has_many :tags, :vote_options
  
  def tags
  	object.tags.pluck(:tag)
  end

  def aws_key
  	return AwsService.get_presignedurl_for_getting(object.aws_key)
  end

  def user
    if !object.anonymous
      return object.user
    end
  end

  def favorite
    if scope.favorites.where(:post_id => object.id).first != nil
      return true
    end
  end
  
end
```

**Comment by zaaroth** [comment]
Try one has_many per line. Place vote_options under it's own has_many

-- Paulo

**Comment by groyoh** [comment]
@cannahum the solution given by @zaaroth is indeed the right one:

```ruby
has_many :tags
has_many :vote_options
```

The first argument is always the association name and the second one the options `Hash`. I'm closing this issue as it is simply a misusage :wink:
