### ISSUE TITLE
AMS 10.2 Throwing NameError for name-spaced object that should not be serialized 

### ISSUE THREAD

**Issue by stephen-puiszis** [rails-api/active_model_serializers#1876]
I'm getting a `NameError` on a service object that should *not* be serialized. This object shares a shares a similar namespace as an object that *should* be serialized. AMS appears to be attempting to serialize any object that shares a namespace to one that is in the serializers in the controller. This is unexpected default behavior and didn't see anything in the documentation regarding this. Even using an empty folder that shares a similar namespace within the `serializers` director, e.g `app/serializers/my_namespace` with `app/services/my_namespace` will throw an error for any object. I have a work-around in place for the time being, which is not namespace the serializer and use a different class name. 

```ruby
NameError (uninitialized constant Api::V1::Givex::CardService):
  app/controllers/api/v1/gift_cards_controller.rb:32:in `assign_gift_card'
```

```ruby
# app/controllers/api/v1/gift_cards_controller.rb
module Api::V1

  class GiftCardsController < BaseController
    before_action :assign_gift_card, only: [:show]

    # GET /api/v1/gift_cards/:givex_number
    def show
      return blank_response if @gift_card.nil?

      if @gift_card.success?
        render json: @gift_card,
               serializer: Api::V1::Givex::CardSerializer,
               status: :ok
      else
        render json: @gift_card.errors.to_json, status: :ok
      end

      private
      
       def assign_gift_card
         return nil unless gift_card_params[:givex_number]

         @gift_card = Givex::CardService.balance(gift_card_params.fetch(:givex_number)).card
       end

    end
```

Service Objects and object to be serialized: 
```ruby
# app/services/givex/card.rb
require "money"

class Givex::Card

  include ActiveModel::Model
  include ActiveModel::Serialization
 
  ...
end


# app/services/givex/card_service.rb
class Givex::CardService < Givex::Base
  
   ...
 
end
```

Folder structure for service objects: 
```
# app/services 
app/services
├── givex
│   ├── card.rb (to be serialized)
│   ├── card_service.rb (to not be serialized)
(omitted non-relevant files)
```

To be consistent, I wanted to set my Givex::Card to be namespaced so it would be consistent throughout the app. So this would be: `Api::V1::Givex::CardSerializer`. However this throws an error on all service objects that shouldn't be serialized in my api controller: 
```
app/serializers (throws error)
└── api
    └── v1
        ├── givex
        │   └── card_serializer.rb
```
Even an empty folder with the same namespace will throw an error: 
```
# app/serializers - throws error
app/serializers
└── api
    └── v1
        ├── gift_card_serializer.rb
        ├── givex (empty folder)
```

Not using the namespace fixes the issue, but this is unexpected behavior. 
```
# app/serializers 
app/serializers
└── api
    └── v1
        ├── gift_card_serializer.rb
```

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*: 10.2 and 10.0

Output of `ruby -e "puts RUBY_DESCRIPTION"`: 

ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

Rails 4.2.7

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

#### Additonal helpful information
*(e.g., Gemfile.lock, configurations, PR containing a failing test, git bisect results)*

**Comment by bf4** [comment]
So, is the problem that `Api::V1::Givex::CardSerializer,` that has an associated `Givex::CardService` looks up the card service serializer as `Api::V1::Givex::CardService` instead of `Givex::CardSerializer`?  I'm having a hard time following what the exact problem is.

**Comment by stephen-puiszis** [comment]
hey @bf4, my apologies. AMS thows an error in the controller because it tries to serialize `Givex::CardService` when there isn't a serializer for it and it should not be serialized. However, there is another object in the controller action that does have a serializer associated with it and should be serialized, `Givex::Card`. These two service objects share a similar namespace and it appears that AMS is assuming `Givex::CardService` should be serialized when I added a `givex` directory within `serializers`, when it in fact, should not. Does that make sense?

**Comment by bf4** [comment]
> Does that make sense?

@stephen-puiszis not quite. Can you share the relevant parts of your serializer(s) and controller render logic?

e.g.

```ruby
class Api::V1::Givex::CardSerializer < ApplicationSerializer
end
```

```ruby
card_service = Givex::CardService.new(Givex::Card)
render json: card_service, serializer: Givex::CardSerializer
```

**Comment by bf4** [comment]
Oh, looking at what part of the stack trace you gave me above, the problem is on the line referenced

```
NameError (uninitialized constant Api::V1::Givex::CardService):
  app/controllers/api/v1/gift_cards_controller.rb:32:in `assign_gift_card'
```

i.e. `         @gift_card = Givex::CardService.balance(gift_card_params.fetch(:givex_number)).card`

should be `::Givex::CardService`

**Comment by remear** [comment]
Closing due to inactivity
