### ISSUE TITLE
"uninitialized constant ActiveModelSerializers (NameError)" while using rspec with a Rails Engine

### ISSUE THREAD

**Issue by steffenschmidt** [rails-api/active_model_serializers#1932]
Unfortunately I get the following error when using rspec inside my engine. ActiveModelSerializers works fine when starting the rails server.

The following error is thrown when running `rspec` via the console:
```
~/Rails/kn/engines/core (active_model_serializers*) $ rspec
/Users/steffen/Rails/kn/config/initializers/active_model_serializer.rb:1:in `<top (required)>': uninitialized constant ActiveModelSerializers (NameError)
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/engine.rb:648:in `block in load_config_initializer'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/engine.rb:647:in `load_config_initializer'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/engine.rb:611:in `each'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/steffen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/steffen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/steffen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/steffen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/steffen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/initializable.rb:44:in `each'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/steffen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `call'
	from /Users/steffen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /Users/steffen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/steffen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/steffen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/steffen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/steffen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/steffen/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/steffen/Rails/kn/config/environment.rb:5:in `<top (required)>'
	from /Users/steffen/Rails/kn/engines/core/spec/rails_helper.rb:3:in `require'
	from /Users/steffen/Rails/kn/engines/core/spec/rails_helper.rb:3:in `<top (required)>'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1394:in `require'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1394:in `block in requires='
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1394:in `each'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1394:in `requires='
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.2/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.2/lib/rspec/core/configuration_options.rb:111:in `each'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.2/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.2/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:99:in `setup'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:86:in `run'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:71:in `run'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/gems/rspec-core-3.5.2/exe/rspec:4:in `<top (required)>'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/bin/rspec:23:in `load'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/bin/rspec:23:in `<main>'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/steffen/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

Versions:
```
ruby (2.3.1)
rails (5.0.0.1) (api-only)
active_model_serializers (0.10.2)
```

Gemfile of main app
```
gem "rails", "~> 5.0.0"
gem "rack-cors"
gem "active_model_serializers", "~> 0.10.0"

# Private Engines
gem "my_project_core", path: "engines/core"
gem "my_project_another_engine", path: "engines/another_engine"
gem "my_project_third_engine", path: "engines/third_engine"
```

Gem spec file of core engine:
```
$:.push File.expand_path("../lib", __FILE__)

# Maintain your gem's version:
require "my_project/core/version"

# Describe your gem and declare its dependencies:
Gem::Specification.new do |s|
  s.name        = "my_project_core"
  s.version     = MyProject::Core::VERSION
  s.summary     = "some text"
  s.description = "some text"

  s.files = Dir["{app,config,db,lib}/**/*", "Rakefile", "README.rdoc"]
  s.test_files = Dir["test/**/*"]

  s.add_dependency "rails", "~> 5.0.0"
  s.add_dependency "devise_token_auth"

  s.add_development_dependency "sqlite3"
  s.add_development_dependency "rspec-rails"
  s.add_development_dependency "factory_girl_rails"
  s.add_development_dependency "database_cleaner"
  s.add_development_dependency "shoulda-matchers"
end
```

rails_helper.rb in core engine:
```
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path("../../../../config/environment", __FILE__)

abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'spec_helper'
require 'rspec/rails'

require 'factory_girl_rails'
require 'database_cleaner'
require 'shoulda/matchers'
require 'devise'

ENGINE_RAILS_ROOT = File.join(File.dirname(__FILE__), '../')
Dir[File.join(ENGINE_RAILS_ROOT, "spec/support/**/*.rb")].each {|f| require f }

ActiveRecord::Migration.maintain_test_schema!

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end

RSpec.configure do |config|
  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.use_transactional_fixtures = true
  config.infer_spec_type_from_file_location!
  config.filter_rails_from_backtrace!

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end

  config.include MyProject::Core::Engine.routes.url_helpers
  config.include FactoryGirl::Syntax::Methods
  config.include Devise::Test::ControllerHelpers, :type => :controller
  config.extend ControllerMacros, :type => :controller
  config.include Requests::JsonHelpers, type: :controller

  config.before(:each, type: :controller) {
    request.headers["HTTP_AUTHORIZATION"] = "Token token=ABC123XYZ"
    request.headers["HTTP_ACCEPT"] = "application/json"
  }
end
```

How to get `rspec` running with `active_model_serializer`-gem? Do you need any more information?

**Comment by NullVoxPopuli** [comment]
do you have a repo we can look at? 

we currently don't have enough information to replicate your issue.

So a repo, or adding enough information here to replicate your issue would be fantastic.

**Comment by steffenschmidt** [comment]
I've updated the above question with some more details because it is a private repo which I can't share.

**Comment by beauby** [comment]
As nothing seems obviously wrong here, I suggest you try to make a minimal rails app that exhibits the behavior and make it available via github so that it's easier to look into your issue.

**Comment by steffenschmidt** [comment]
I've extracted some code to a minimal rails app. You can look at this here:
https://github.com/steffenschmidt/active_model_serializers_with_rspec

**Comment by richmolj** [comment]
@steffenschmidt I think this is more of an engine testing thing than anything else. You're engine's gemspec isn't specifying AMS, nor is it required in a spec helper or environment file. I don't see where the engine's specs would be loading the gems defined in the outer application's Gemfile.

This is also why it works fine when starting the rails server - all the dependencies are actually getting loaded, because the 'starting point' is the outer application instead of the inner engine.

Make sense?

**Comment by steffenschmidt** [comment]
@richmolj Now I updated the repository so that the gem is loaded in the core engine and moved the initializer to the core engine as well. Now I get errors at both sides: `rails server` and `rspec`:

```
/Users/steffen/Rails/active_model_serializers_with_rspec/engines/core/config/initializers/active_model_serializer.rb:1:in `<top (required)>': uninitialized constant ActiveModelSerializers (NameError)
```

**Comment by richmolj** [comment]
An engine, like any gem, will not autoload its dependencies. You are specifying AMS as a dependency, but not loading it. Typically you would `require 'active_model_serializers'` [in your library's lib/mylib.rb](https://github.com/steffenschmidt/active_model_serializers_with_rspec/blob/master/engines/core/lib/kn_core.rb).

For instance, here is where AMS loads activemodel dependency: https://github.com/rails-api/active_model_serializers/blob/master/lib/active_model_serializers.rb#L1

This issue really seems more to do with how to develop and test engines than anything specific to AMS, so I'm going to close the issue. If I'm incorrect please let me know so we can reopen.

**Comment by steffenschmidt** [comment]
How could I missed that? Thanks for your help!
