### ISSUE TITLE
Status code 500 when rendering hash, Rendered ActiveModel::Serializer::Null with Hash

### ISSUE THREAD

**Issue by januszm** [rails-api/active_model_serializers#2024]
#### Expected behavior vs actual behavior

In my controller I still want to render an arbitrary Hash as json, so while in one action I'd like to use AMS implicitly with ```render json: @object``` , I'd still like to use something like ```render json: { message: message }, status: status``` without hitting the AMS or using some very simple 'passthrough' serializer. What I 

#### Steps to reproduce
*(e.g., detailed walkthrough, runnable script, example application)*

```ruby
def some_action
  ...
  message = 'Incorrect URL'
  status = :bad_request
  render json: { message: message }, status: status
end
```

#### Environment

ActiveModelSerializers Version *(commit ref if not on tag)*:  0.10.4

Output of `ruby -e "puts RUBY_DESCRIPTION"`:  ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]

OS Type & Version:  Mac OS X 10.11.6

Integrated application and version *(e.g., Rails, Grape, etc)*:  Rails 5.0.1

#### Backtrace
*(e.g., provide any applicable backtraces from your application)*

```
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.14ms)
Completed 500 Internal Server Error in 45ms (Views: 7.4ms | ActiveRecord: 0.0ms)
```

It should not respond with status 500, this is not an error. I tried a workaround like ```    render inline: { message: message }.to_json, status: status, content_type: 'application/json'
``` with no success.

**Comment by bf4** [comment]
@januszm yeah, this is an annoying issue we need to fix. In the meantime, you should be able to `render json: { message: message }.to_json, status: :bad_request`

**Comment by bf4** [comment]
I don't think it actually is doing any transformation, just checking if it can find a serializer, and then returning the value when it can't, but it goes through the logger when doing that leaving that annoying message

**Comment by groyoh** [comment]
@bf4 one other issue though is that when specifying `adapter: false # or nil`, `SerializableResource` still tries to fetch a serializer whereas it should not.

**Comment by januszm** [comment]
@bf4 thanks actually `to_json` was not needed after that hash.

Anyway, looks like the `Null` serializer is used >only< here, in the logger:
`lib/active_model_serializers/logging.rb:85:        serializer: serializer || ActiveModel::Serializer::Null`

I've just tried a short circuit in LogSubscriber#render and removing the Null serializer , helped but I'm not sure where else you use that Null serializer. 

```ruby
    def notify_render_payload
      {
        serializer: serializer,
        adapter: adapter || ActiveModelSerializers::Adapter::Null
...
    class LogSubscriber < ActiveSupport::LogSubscriber
      def render(event)
        return unless event.payload[:serializer]
        ...
```
We could mention that in the docs (eg. for "hash" we'll see Null serializer mentioned in the logs).

Also, it feels like it shouldn't hit the `SerializableResource` unless the serialized resource is a model or association.

**Comment by groyoh** [comment]
@januszm this should probably not appear in AMS logs or should appear as something like `rendered without AMS: no serializer found`. That is way clearer than specifying `rended with Null serializer` and mention it in the docs. There are some fixes to be done here.

**Comment by januszm** [comment]
@groyoh yes I agree, that's why I tried the patch above which removes the message from the logs entirely (notice `return unless event.payload[:serializer]`). I also agree that there are some fixes to be done ;) I mentioned that in my last phrase, I wouldn't touch the SerializableResource class unless the object that we want to serialize is somehow related to the ActiveModel / ActiveRecord.

**Comment by bf4** [comment]
> this should probably not appear in AMS logs
@groyoh yes, it's an undesired effect of a change (bug fix) in how serializable resource works in the controller... 
as https://github.com/rails-api/active_model_serializers/issues/2024#issuecomment-271719008

>  specifying adapter: false # or nil, SerializableResource still tries to fetch a serializer 

```ruby

        warn 'ActionController::Serialization#use_adapter? has been removed. '\
          "Please pass 'adapter: false' or see ActiveSupport::SerializableResource.new"
        options[:adapter] = false
    
```

yeah, I guess `get_serializer` could return early for that... code design...

https://github.com/rails-api/active_model_serializers/blob/93ca27fe444c3a940890cb7a4dedbd8369f481f3/lib/action_controller/serialization.rb#L45-L48

**Comment by travega** [comment]
Does anyone know has a fix been identified for this issue yet? Or a work around? Looks like it's ready for PR for a couple of months now 🤔

**Comment by bf4** [comment]
@travega Not fixed. Not one's done it :)

I have these notes in my initializer that might be helpful. If you're using an exceptions_app that inherits from action controller, you may need to set `serialization_scope :view_context # so ActiveModelSerializers doesn't call current_user`

```ruby
ActiveSupport.on_load(:action_controller) do
  require 'active_model_serializers/register_jsonapi_renderer'
  ActiveModelSerializers.eager_load! if Rails.env.production?
  ActiveModelSerializers::Adapter::JsonApi.eager_load! if Rails.env.production?
  require 'active_model/serializer/null'
  ActiveModel::Serializer::Null
  # https://github.com/rails-api/active_model_serializers/blob/a032201a91cbca407211bca0392ba881eef1f7ba/lib/active_model_serializers/logging.rb#L83-L87
  #   def notify_render_payload
  #     {
  #       serializer: serializer || ActiveModel::Serializer::Null,
  #       adapter: adapter || ActiveModelSerializers::Adapter::Null
  #     }
  #   end
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:85:in `notify_render_payload'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:78:in `notify_render'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:21:in `block (2 levels) in instrument_rendering'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:97:in `tag_logger'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:20:in `block in instrument_rendering'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.10.2/lib/active_model_serializers/logging.rb:68:in `block (2 levels) in notify'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/renderers.rb:116:in `block in <module:Renderers>'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.10.2/lib/action_controller/serialization.rb:53:in `block (2 levels) in <module:Serialization>'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/renderers.rb:45:in `block in _render_to_body_with_renderer'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/renderers.rb:41:in `_render_to_body_with_renderer'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/remotipart-1.2.1/lib/remotipart/render_overrides.rb:14:in `render_with_remotipart'
  #   /srv/rails_server/app/controllers/exception_handler/exception_controller.rb:21:in `block (2 levels) in show'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/mime_responds.rb:217:in `call'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.7.1/lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
  #   /srv/rails_server/app/controllers/exception_handler/exception_controller.rb:20:in `show'
  #   /srv/rails_server/lib/core_extensions/actioncontroller/request_logging.rb:12:in `process_action'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/lograge-0.4.1/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:22:in `call'
  #   /srv/rails_server/vendor/lib/rack_headers.rb:72:in `_call'
  #   /srv/rails_server/vendor/lib/rack_headers.rb:68:in `call'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/skylight-1.0.0/lib/skylight/middleware.rb:61:in `call'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/puma-3.5.2/lib/puma/configuration.rb:225:in `call'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/puma-3.5.2/lib/puma/server.rb:569:in `handle_request'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/puma-3.5.2/lib/puma/server.rb:406:in `process_client'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/puma-3.5.2/lib/puma/server.rb:271:in `block in run'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/puma-3.5.2/lib/puma/thread_pool.rb:116:in `call'
  #   /srv/rails_server/vendor/bundle/ruby/2.2.0/gems/puma-3.5.2/lib/puma/thread_pool.rb:116:in `block in spawn_thread't
end
```

**Comment by TranBaVinhSon** [comment]
I have the same problem. When I use AMS implicitly with `render json: @data`, it's work perfect. But when I use it in hash:
```ruby
def json_response messages, data, status = :ok
    render json: {
      messages: messages,
      data: data
    }, status: status
end
```
I got error: `Rendered ActiveModel::Serializer::Null with Hash `.
Does anyone solve it ?

**Comment by bf4** [comment]
Call to_json on your hash

B mobile phone

**Comment by TranBaVinhSon** [comment]
@bf4 It doesn't work :(
```ruby
def json_response messages, data, status = :ok
    render json: {
      messages: messages,
      data: data
    }.to_json, status: status
end
```

**Comment by bf4** [comment]
Well, without any more details on how it doesn't work I don't have anything tp add except don't serialize hashes... uses either records or strings

B mobile phone

**Comment by TranBaVinhSon** [comment]
@bf4 I'm sorry for my mistake 

Response Function
```ruby
def json_response messages, data, status = :ok
    render json: {
      messages: messages,
      data: data
    }.to_json, status: status
  end
```
Controller
```ruby
  def index
    companies = Company.all
    logger.info " #{companies[0].to_json}"
    # render json: companies
    json_response I18n.t("companies.index.success"), {companies: companies}, :ok
  end
```
ActiveModel::Serializer 
```ruby
class CompanySerializer < ActiveModel::Serializer
  attributes :id, :name, :number_employee, :address, :website, :description

  belongs_to :industry
  belongs_to :province
end
```

It's only work when I use `render json: companies`

**Comment by sree300994** [comment]
Actually to_json worked for me while sending hash in render `render json: @status.to_json`

**Comment by bf4** [comment]
@sree300994 

>  after rendering but it should not be use to_json like that

Strongly disagree. AMS by design ignores any string, such as the result of `to_json`.  So, this is a natural way to skip AMS.  AMS doesn't serialize a Hash because it's a primitive, not a model. Discussed in readme.

**Comment by sree300994** [comment]
yaa its correct maybe their might be change in naming convention of serializer. what i mean is if the controller in normal controllers folder and the serializer might be created in versioning means it will through this error. The example is `class UsersController < ApplicationController` this is how i created controller but the serializer i created is like `class Api::V1::UserSerializer < ActiveModel::Serializer` by creating like this it thrown me error, after changing serializer to `class UserSerializer < ActiveModel::Serializer` this, my error disappeared

**Comment by awadhwana** [comment]
> yaa its correct maybe their might be change in naming convention of serializer. what i mean is if the controller in normal controllers folder and the serializer might be created in versioning means it will through this error. The example is `class UsersController < ApplicationController` this is how i created controller but the serializer i created is like `class Api::V1::UserSerializer < ActiveModel::Serializer` by creating like this it thrown me error, after changing serializer to `class UserSerializer < ActiveModel::Serializer` this, my error disappeared


When serializing a model inside a namespace, such as Api::V1::Post, ActiveModelSerializers will expect the corresponding serializer to be inside the same namespace (namely Api::V1::PostSerializer).

**Comment by tisba** [comment]
Any update on this one? I'm bouncing back and forth between "adding .to_json everywhere" and monkey patching ASM and I'd prefer not having to patch it.

I do understand that the bigger issue should be addressed, but is there a reason not to remove this logging output as a first step? Happy to provide a PR using what @januszm has commented on [6 years ago 👴☝️](https://github.com/rails-api/active_model_serializers/issues/2024#issuecomment-272134442).

In case somebody wants to get rid of the logging **without patching ASM**, finding places where this has been missed is relatively easy (at least with a decent test suite):

```ruby
unless Rails.env.production?
  ActiveSupport::Notifications.subscribe(ActiveModelSerializers::Logging::RENDER_EVENT) do |*args|
    event = ActiveSupport::Notifications::Event.new(*args)

    if event.payload[:serializer] == ActiveModel::Serializer::Null
      raise "Used 'render json: …' with a Hash! Make sure to pass a model/collection or a String!"
    end
  end
end
```

**Comment by bf4** [comment]
@tisba AMS has a linter to validate that all inputs are valid. It expects a Model which passes the linter. I appreciate the time and effort you're putting in. I won't accept a change which treats a Hash as a serializable input for AMS, but will accept a PR which makes the dev experience better.

**Comment by tisba** [comment]
> AMS has a linter to validate that all inputs are valid.

Damn, didn't kew that  🤦‍♂️ 😁  Thanks!

> I won't accept a change which treats a Hash as a serializable input for AMS, but will accept a PR which makes the dev experience better.

That was my thought exactly. I'll take a look and shoot you a draft.

**Comment by tisba** [comment]
The AMS source code is a little bit more "convoluted" then I thought 😅 

From what I can see there might be two "simple" options. If you could give me a hint if any of those directions feels right, @bf4. Both diff's don't break any tests for me (via `rake test`).

Based on @januszm's suggestion we could do this (basically just skipping the logging):

```diff
diff --git i/lib/active_model_serializers/logging.rb w/lib/active_model_serializers/logging.rb
index ad79743b..f51d615c 100644
--- i/lib/active_model_serializers/logging.rb
+++ w/lib/active_model_serializers/logging.rb
@@ -106,6 +106,8 @@ def logger_tagged_by_active_model_serializers?
 
     class LogSubscriber < ActiveSupport::LogSubscriber
       def render(event)
+        return if event.payload[:serializer] == ActiveModel::Serializer::Null
+        
         info do
           serializer = event.payload[:serializer]
           adapter = event.payload[:adapter]
```

Alternatively, we could also cut ASM out of the process WAY before and just don't do anything if the given `resource` is a `Hash`:

```diff
diff --git i/lib/action_controller/serialization.rb w/lib/action_controller/serialization.rb
index 904c758c..4197144b 100644
--- i/lib/action_controller/serialization.rb
+++ w/lib/action_controller/serialization.rb
@@ -65,6 +65,8 @@ def use_adapter?
 
     [:_render_option_json, :_render_with_renderer_json].each do |renderer_method|
       define_method renderer_method do |resource, options|
+        super(resource, options) if resource.is_a?(Hash)
+
         options.fetch(:serialization_context) do
           options[:serialization_context] = ActiveModelSerializers::SerializationContext.new(request, options)
         end
```

**Comment by bf4** [comment]
I guess the question is one of intention.  When you pass in Hash, do you expect AMS to do something with it? I don't. So, since that's the case, I guess we adjust how we hook into the json renderer.  But maybe people want to raise errors or warn on unexpected inputs?

looking at https://github.com/rails-api/active_model_serializers/blob/0-10-stable/lib/action_controller/serialization.rb#L66-L74 right now I see we have

```ruby
    [:_render_option_json, :_render_with_renderer_json].each do |renderer_method|
      define_method renderer_method do |resource, options|
        options.fetch(:serialization_context) do
          options[:serialization_context] = ActiveModelSerializers::SerializationContext.new(request, options)
        end
        serializable_resource = get_serializer(resource, options)
        super(serializable_resource, options)
      end
    end
```

first off, really, we should, imho, alias the method if it exists, else override it, but that ship has sailed

I suppose it could be changed to

```ruby
    [:_render_option_json, :_render_with_renderer_json].each do |renderer_method|
      define_method renderer_method do |resource, options|
        if ams_can_serialize?(resource)
          options.fetch(:serialization_context) do
            options[:serialization_context] = ActiveModelSerializers::SerializationContext.new(request, options)
          end
          serializable_resource = get_serializer(resource, options)
          super(serializable_resource, options)
        else
          super(resource, options) 
        end
      end
    end

    def ams_can_serialize?(resource)
      return false if resource.is_a?(Hash)
      return false if resource.is_a?(Array) && resource.any? {|element| element.is_a?(Hash) }
      true
    end
```

Or I guess we could add an escape valve on the logger "yes, I know I passed in a hash to AMS. ignore"

Or write your own renderer? https://www.benjaminfleischer.com/2015/06/02/understanding-rails-model-serializers/
