### ISSUE TITLE
In Rails JSON.dump does not work with ActiveModel::Serializer instance, while MultiJson does.

### ISSUE THREAD

**Issue by mlangenberg** [rails-api/active_model_serializers#340]
The fix for this issue might be found in Rails or JSON, but I am reporting it since I ran into it while working with AMS. 

Bug reproduced with following gem versions.
- ruby-1.9.3p392
- rails-3.2.13
- active_model_serializers-0.8.1
- multi_json-1.7.7
- json-1.8.0

``` ruby
MultiJson.dump(
  ActiveModel::Serializer.new(Object.new)
) #=> "{\"serializer\":{}}" 
```

``` ruby
JSON.dump(
  ActiveModel::Serializer.new(Object.new)
) #=> NoMethodError: undefined method `fetch' for #<JSON::Ext::Generator::State:0x007fd07a5f9928>
  # from /active_model_serializers-0.8.1/lib/active_model/serializer.rb:340:in `as_json'
  # from /activesupport-3.2.13/lib/active_support/json/encoding.rb:47:in `block in encode'
  # from /activesupport-3.2.13/lib/active_support/json/encoding.rb:77:in `check_for_circular_references'
  # from /activesupport-3.2.13/lib/active_support/json/encoding.rb:46:in `encode'
  # from /activesupport-3.2.13/lib/active_support/json/encoding.rb:31:in `encode'
  # from /activesupport-3.2.13/lib/active_support/core_ext/object/to_json.rb:16:in `to_json'
  # from /active_model_serializers-0.8.1/lib/active_model/serializer.rb:333:in `to_json'
  # from /json-1.8.0/lib/json/common.rb:223:in `generate'
  # from /json-1.8.0/lib/json/common.rb:223:in `generate'
  # from /json-1.8.0/lib/json/common.rb:394:in `dump'
  # from (irb):9
  # from /railties-3.2.13/lib/rails/commands/console.rb:47:in `start'
  # from /railties-3.2.13/lib/rails/commands/console.rb:8:in `start'
  # from /railties-3.2.13/lib/rails/commands.rb:41:in `<top (required)>'
  # from script/rails:6:in `require'
  # from script/rails:6:in `<main>'
```

You will run into this when using Sidekiq-2.12 in combination with AMS. Since Sidekiq-2.12 it uses JSON instead of multi_json for serializing arguments passed to a Sidekiq worker.

> Remove usage of multi_json as json is now robust on all platforms.
> https://github.com/mperham/sidekiq/blob/master/Changes.md#2120

I think the root cause lies in Rails doing an override of `as_json` somewhere.

**Comment by mhuggins** [comment]
I'm still seeing this error on Rails 3.2.22 with ActiveModel Serializers 0.8.3.  Am I missing something?

```ruby
serializer = Service::Notifications::NewsroomSerializer.new(newsroom)
serializer.to_json
# => "{\"name\":\"Huggie\",\"subdomain\":\"huggie\"}" 

JSON.dump(s)
# => NoMethodError: undefined method `fetch' for #<JSON::Ext::Generator::State:0x007faf44dc3048>

MultiJson.dump(s)
# => "{\"name\":\"Huggie\",\"subdomain\":\"huggie\"}" 
```
