### ISSUE TITLE
0.9.0.alpha yields 'NoMethodError - undefined method `each_with_object''

### ISSUE THREAD

**Issue by ericpeters0n** [rails-api/active_model_serializers#545]
(Implementation works flawlessly in 0.8.1)

```
NoMethodError - undefined method `each_with_object' for :replies:Symbol:
  /Users/Eric/.rvm/gems/ruby-1.9.2-p320@linksee_demo/bundler/gems/active_model_serializers-2e31a141252a/lib/active_model/serializer.rb:125:in `attributes'
  /Users/Eric/.rvm/gems/ruby-1.9.2-p320@linksee_demo/bundler/gems/active_model_serializers-2e31a141252a/lib/active_model/serializer.rb:195:in `serializable_object'
  /Users/Eric/.rvm/gems/ruby-1.9.2-p320@linksee_demo/bundler/gems/active_model_serializers-2e31a141252a/lib/active_model/array_serializer.rb:41:in `block in serializable_object'
  (gem) activerecord-3.2.8/lib/active_record/relation/delegation.rb:6:in `map'
  /Users/Eric/.rvm/gems/ruby-1.9.2-p320@linksee_demo/bundler/gems/active_model_serializers-2e31a141252a/lib/active_model/array_serializer.rb:40:in `serializable_object'
  /Users/Eric/.rvm/gems/ruby-1.9.2-p320@linksee_demo/bundler/gems/active_model_serializers-2e31a141252a/lib/active_model/serializable.rb:9:in `as_json'
  (gem) activesupport-3.2.8/lib/active_support/json/encoding.rb:47:in `block in encode'
  (gem) activesupport-3.2.8/lib/active_support/json/encoding.rb:77:in `check_for_circular_references'
  (gem) activesupport-3.2.8/lib/active_support/json/encoding.rb:46:in `encode'
  (gem) activesupport-3.2.8/lib/active_support/json/encoding.rb:31:in `encode'
  (gem) activesupport-3.2.8/lib/active_support/core_ext/object/to_json.rb:16:in `to_json'
  (gem) actionpack-3.2.8/lib/action_controller/metal/renderers.rb:93:in `block in <module:Renderers>'
  /Users/Eric/.rvm/gems/ruby-1.9.2-p320@linksee_demo/bundler/gems/active_model_serializers-2e31a141252a/lib/action_controller/serialization.rb:47:in `_render_option_json'
  (gem) actionpack-3.2.8/lib/action_controller/metal/renderers.rb:35:in `block in _handle_render_options'
  /Users/Eric/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/set.rb:222:in `block in each'
  /Users/Eric/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/set.rb:222:in `each'
  (gem) actionpack-3.2.8/lib/action_controller/metal/renderers.rb:32:in `_handle_render_options'
  (gem) actionpack-3.2.8/lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  (gem) actionpack-3.2.8/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  (gem) actionpack-3.2.8/lib/abstract_controller/rendering.rb:88:in `render'
  (gem) actionpack-3.2.8/lib/action_controller/metal/rendering.rb:16:in `render'
  (gem) actionpack-3.2.8/lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  (gem) activesupport-3.2.8/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /Users/Eric/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/benchmark.rb:310:in `realtime'
  (gem) activesupport-3.2.8/lib/active_support/core_ext/benchmark.rb:5:in `ms'
  (gem) actionpack-3.2.8/lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  (gem) actionpack-3.2.8/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  (gem) activerecord-3.2.8/lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  (gem) actionpack-3.2.8/lib/action_controller/metal/instrumentation.rb:39:in `render'
 ```

Serializer in question is:
```
class CommentSerializer < ActiveModel::Serializer
	attributes :body, :created_at, :user_id, :user_name, :user_avatar, :num_replies, :replies
	def filter(keys)
		object.has_children? ? keys : keys.delete(:replies)
	end
	def user_name
		object.user.name
	end
	def user_avatar
		object.user.avatar
	end
	def num_replies
		object.has_children? ? object.children.size : 0
	end
	def replies
		object.has_children? ? object.children : []
	end
end
```

Removing the 'replies' method and attribute results in the code failing similarly with a
```
NoMethodError - undefined method `each_with_object' for nil:NilClass:
```
(Again, this works without issue on 0.8.1)

**Comment by beauby** [comment]
Closing this one for now, feel free to reopen if needed.
