### ISSUE TITLE
Including AMS 0.9.0 gem in Rails 4.2.0.beta1 breaks "get :index" in tests

### ISSUE THREAD

**Issue by lagartoflojo** [rails-api/active_model_serializers#643]
Hello,
In a newly created Rails 4.2.0.beta1 app, simply adding the AMS gem breaks a simple test:

```
$ rails new testapp
$ cd testapp
$ rails g controller Dashboard index
$ rake
Run options: --seed 13216

# Running:

.

Finished in 0.430643s, 2.3221 runs/s, 2.3221 assertions/s.

1 runs, 1 assertions, 0 failures, 0 errors, 0 skips

# Add gem 'active_model_serializers' to Gemfile
$ bundle && BACKTRACE=true rake
# (...skipped bundle output...)
Run options: --seed 44299

# Running:

E

Finished in 0.009727s, 102.8084 runs/s, 0.0000 assertions/s.

  1) Error:
DashboardControllerTest#test_should_get_index:
NoMethodError: undefined method `clear' for nil:NilClass
    (...)/gems/actionpack-4.2.0.beta1/lib/action_controller/test_case.rb:69:in `block in reset_template_assertion'
    (...)/gems/actionpack-4.2.0.beta1/lib/action_controller/test_case.rb:68:in `each'
    (...)/gems/actionpack-4.2.0.beta1/lib/action_controller/test_case.rb:68:in `reset_template_assertion'
    (...)/gems/actionpack-4.2.0.beta1/lib/action_controller/test_case.rb:63:in `process'
    (...)/gems/active_model_serializers-0.9.0/lib/action_controller/serialization_test_case.rb:25:in `process'
    (...)/gems/actionpack-4.2.0.beta1/lib/action_controller/test_case.rb:504:in `get'
    (...)/testapp/test/controllers/dashboard_controller_test.rb:5:in `block in <class:DashboardControllerTest>'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

Where DashboardControllerTest is just the default generated by Rails:

```ruby
require 'test_helper'

class DashboardControllerTest < ActionController::TestCase
  test "should get index" do
    get :index
    assert_response :success
  end

end
```

**Comment by NullVoxPopuli** [comment]
closing for now. please reopen if this is still an issue.
