### ISSUE TITLE
update initializer syntax

### ISSUE THREAD

**Issue by ballPointPenguin** [rails-api/active_model_serializers#781]
In Rails 4.2 (and maybe ealier?)

the following will not work in an initializer:
```ruby
ActiveModel::Serializer.config.adapter = :json_api
```

instead you should use:
```ruby
ActiveModel::Serializer.setup do |config|
  config.adapter = :json_api
end
```

If I was certain about the version requirements I would PR against the README.
Does anyone know for sure when the former syntax was deprecated?

**Comment by ballPointPenguin** [comment]
relates to #695

**Comment by ballPointPenguin** [comment]
Hmm... After update to AMS-master (0.10.x) the former syntax works and the latter is problematic.
I guess this has nothing to do with Rails 4.2, but I feel a little like I'm chasing my own tail.

**Comment by mariozig** [comment]
@ballPointPenguin Thanks for this issue and for posting the solution.  I actually just ran into the exact same thing... 

With active_model_serializers (0.9.3) i get errors like this when i use the `config.adapter..` syntax: 

```
➜  dr_phil git:(master) ✗ rake db:migrate
/Users/mariozig/Desktop/dr_phil/config/initializers/json_api_adapter.rb:1:in `<top (required)>': undefined method `config' for ActiveModel::Serializer:Class (NoMethodError)
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:652:in `block in load_config_initializer'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:651:in `load_config_initializer'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `each'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:615:in `block in <class:Engine>'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /Users/mariozig/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
  from /Users/mariozig/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  from /Users/mariozig/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
  from /Users/mariozig/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
  from /Users/mariozig/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
  from /Users/mariozig/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
  from /Users/mariozig/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
  from /Users/mariozig/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
  from /Users/mariozig/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
  from /Users/mariozig/Desktop/dr_phil/config/environment.rb:5:in `<top (required)>'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/spring-1.2.0/lib/spring/application.rb:92:in `preload'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/spring-1.2.0/lib/spring/application.rb:143:in `serve'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
  from /Users/mariozig/.rvm/gems/ruby-2.2.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
  from /Users/mariozig/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from /Users/mariozig/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  from -e:1:in `<main>'
```


Same syntax in active_model_serializers (0.10.0.pre) works fine.
