### ISSUE TITLE
Loading minitest in production mode

### ISSUE THREAD

**Issue by dlangevin** [rails-api/active_model_serializers#814]
AMS seems to be loading minitest in all environments, which is giving me a warning due to  `minitest/parallel.rb` using threads.  I would think that the test support code should be loaded conditionally?  Happy to put that in if you agree

```bash
[6761] Puma starting in cluster mode...
[6761] * Version 2.11.1 (ruby 2.1.2-p95), codename: Intrepid Squirrel
[6761] * Min threads: 5, max threads: 5
[6761] * Environment: production
[6761] * Process workers: 2
[6761] * Preloading application
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/minitest-5.5.1/lib/minitest/parallel.rb:21:in `block in initialize'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/minitest-5.5.1/lib/minitest/parallel.rb:20:in `times'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/minitest-5.5.1/lib/minitest/parallel.rb:20:in `each'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/minitest-5.5.1/lib/minitest/parallel.rb:20:in `map'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/minitest-5.5.1/lib/minitest/parallel.rb:20:in `initialize'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/minitest-5.5.1/lib/minitest.rb:23:in `new'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/minitest-5.5.1/lib/minitest.rb:23:in `<module:Minitest>'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/minitest-5.5.1/lib/minitest.rb:9:in `<top (required)>'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.0/lib/active_support/test_case.rb:2:in `<top (required)>'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:443:in `<module:ActionController>'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:9:in `<top (required)>'
/Users/dlangevin/Documents/Projects/vericred/vendor/bundle/ruby/2.1.0/gems/active_model_serializers-0.9.3/lib/active_model_serializers.rb:15:in `block in <top (required)>'
```

**Comment by bf4** [comment]
Is this still a problem?  Please re-open if it is.  I was unable to verify.
