### ISSUE TITLE
0.8.x has_one association with the name 'instrument' fails

### ISSUE THREAD

**Issue by varblob** [rails-api/active_model_serializers#815]
I think it maybe because the association is called instrument and when it sends to the source_serializer it calls the internal instrument function.

```
ArgumentError Exception: wrong number of arguments (0 for 1..2)
.rvm/gems/ruby-2.1.4/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:494:in `instrument'
.rvm/gems/ruby-2.1.4/gems/active_model_serializers-0.8.3/lib/active_model/serializer/associations.rb:71:in `associated_object'
.rvm/gems/ruby-2.1.4/gems/active_model_serializers-0.8.3/lib/active_model/serializer/associations.rb:224:in `serialize_ids'
.rvm/gems/ruby-2.1.4/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:419:in `include!'
.rvm/gems/ruby-2.1.4/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:367:in `block in include_associations!'
.rvm/gems/ruby-2.1.4/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:366:in `each_key'
.rvm/gems/ruby-2.1.4/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:366:in `include_associations!'
.rvm/gems/ruby-2.1.4/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:480:in `_serializable_hash'
.rvm/gems/ruby-2.1.4/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:361:in `serializable_hash'
.rvm/gems/ruby-2.1.4/gems/active_model_serializers-0.8.3/lib/active_model/serializer.rb:345:in `as_json'
```

Monkey patch solution was to add
``` ruby
def instrument
  object.instrument
end
```
to the serializer, seems to be working so far...

**Comment by pmeno** [comment]
I can recreate this.

**Comment by varblob** [comment]
Thanks for checking into it.  I don't need notifications for the moment so... yay!  I'm gonna close this since I don't think it's going to affect a lot of people.
