### ISSUE TITLE
Problem with each_serializer: foo and has_many associations

### ISSUE THREAD

**Issue by hderms** [rails-api/active_model_serializers#870]
So it seems like if you do something like
``` ruby
render json: foo, each_serializer: FooSerializer

#with this serializer
class FooSerializer
   attributes :something
   has_many :bars
end
class BarSerializer
end
```
you will get an error like `undefined method 'something' for #<Bar:0x007f8c08d5d1f8>`

The regression appears to have been introduced between the following commits:

https://github.com/rails-api/active_model_serializers/compare/a8243761fedbf...48ed7

I believe the issue is in lib/active_model/serializer.rb in `def each_assocation` where we do `options.merge(serializer_from_options(association_options))` which causes the association to be serialized with the option `each_serializer: FooSerializer`

**Comment by JoshSmith** [comment]
@hderms would you have time to open up a PR with a failing test of some sort? Even if you don't necessarily have time to fix it, at least that's a good starting point for someone.

Thanks!

**Comment by kurko** [comment]
What AMS version is this?

**Comment by prasadsurase** [comment]
@hderms, you have specified 
```ruby
render json: foo, each_serializer: FooSerializer
```
Is foo a single object or a collection of objects?

```ruby
unless File.exist?('Gemfile')
  File.write('Gemfile', <<-GEMFILE)
   source 'https://rubygems.org'

   ruby '2.2.1'

   gem 'rails' , '4.2.1'
   gem 'arel'
   gem 'sqlite3'
   gem 'active_model_serializers', '0.9.3'
   gem 'pry'
  GEMFILE

  system 'bundle'
end

require 'bundler'
Bundler.setup(:default)

require 'active_record'
require 'active_model_serializers'
require 'minitest/autorun'
require 'logger'

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :authors, force: true  do |t|
    t.string :name
  end

  create_table :books, force: true  do |t|
    t.integer :author_id
    t.string :name
  end
end

class Author < ActiveRecord::Base
  has_many :books

  validates :name, presence: true
end

class Book < ActiveRecord::Base
  belongs_to :author

  validates :name, :author_id, presence: true
end

class AuthorSerializer < ActiveModel::Serializer
  attributes :name

  has_many :books
end

class BookSerializer < ActiveModel::Serializer
  attributes :name
end

class BugTest < Minitest::Test
  def test_filter_method
    author_1 = Author.create!(name: 'Ernest Hemingway')
    book_1 = Book.create!(name: 'The old man and the sea.', author: author_1)
    book_2 = Book.create!(name: 'The sun also rises.', author: author_1)

    author_2 = Author.create!(name: 'Charles Dickens')
    book_3 = Book.create!(name: 'A christmas carol.', author: author_2)
    book_4 = Book.create!(name: 'Oliver Twist.', author: author_2)

    assert_equal AuthorSerializer.new(author_2).to_json, {author: {name: author_2.name, books: [{name: book_3.name}, {name: book_4.name}]}}.to_json

    assert_equal ActiveModel::ArraySerializer.new(Author.all, each_serializer: AuthorSerializer).to_json, [{name: author_1.name, books: [{name: book_1.name}, {name: book_2.name}]}, {name: author_2.name, books: [{name: book_3.name}, {name: book_4.name}]}].to_json
  end
end
```

**Comment by bf4** [comment]
Some more info, we're using the JSON serializer, not json-api, and the ref we were working with was a8243761fedbf and broken with 48ed7

**Comment by bf4** [comment]
Given:

```ruby
ActiveModel::Serializer.config.adapter = ActiveModel::Serializer::Adapter::Json
class Item < ActiveRecord::Base
  has_many :owners
end
class Owner < ActiveRecord::Base
  belongs_to :item
end
class ItemSerializer < ActiveModel::Serializer
  attributes :id, :name, :last_activity_at
  has_many :owners
end
class OwnerSerializer < ActiveModel::Serializer
  attribute :id, :name
  belongs_to :item
end
class ItemsController
  def show
    render json: Item.first, root: "items", status: :ok, each_serializer: ItemSerializer
  end
end
```

Going from [https://github.com/rails-api/active_model_serializers/commit/a8243761fedbff9877a957fe9b5f21e644bb8fee](https://github.com/rails-api/active_model_serializers/commit/a8243761fedbff9877a957fe9b5f21e644bb8fee) to [https://github.com/rails-api/active_model_serializers/commits/48ed7cf](https://github.com/rails-api/active_model_serializers/commits/48ed7cf) causes the render to fail by attempting to use the `ItemSerializer` to serialize each of the Owners.  The work around is either

1. change the ItemSerializer to

```ruby
has_many :owners, serializer: OwnerSerializer
```

OR

2. remove the `each_serializer` from the controller

```ruby
render json: Item.first, root: "items", status: :ok
```

but this probably shouldn't be necessary, no?

This is on Rails 4.2.0 and 4.2.1 and CRuby 2.1.5 and 2.2.2

Here's a stacktrace

```json
 "Full Trace": [
          {
            "id": 0,
            "trace": "bundle/ruby/2.2.0/gems/activemodel-4.2.1/lib/active_model/attribute_methods.rb:433:in `method_missing'"
          },
          {
            "id": 1,
            "trace": "app/serializers/item_serializer.rb:22:in `last_activity_at'"
          },
          {
            "id": 2,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer.rb:200:in `block in attributes'"
          },
          {
            "id": 3,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer.rb:198:in `each'"
          },
          {
            "id": 4,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer.rb:198:in `each_with_object'"
          },
          {
            "id": 5,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer.rb:198:in `attributes'"
          },
          {
            "id": 6,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer/adapter/json.rb:22:in `block (3 levels) in serializable_hash'"
          },
          {
            "id": 7,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer/adapter.rb:53:in `cache_check'"
          },
          {
            "id": 8,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer/adapter/json.rb:21:in `block (2 levels) in serializable_hash'"
          },
          {
            "id": 9,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer/array_serializer.rb:5:in `each'"
          },
          {
            "id": 10,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer/array_serializer.rb:5:in `each'"
          },
          {
            "id": 11,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer/adapter/json.rb:20:in `map'"
          },
          {
            "id": 12,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer/adapter/json.rb:20:in `block in serializable_hash'"
          },
          {
            "id": 13,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer.rb:224:in `call'"
          },
          {
            "id": 14,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer.rb:224:in `block in each_association'"
          },
          {
            "id": 15,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer.rb:208:in `each'"
          },
          {
            "id": 16,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer.rb:208:in `each_association'"
          },
          {
            "id": 17,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer/adapter/json.rb:17:in `serializable_hash'"
          },
          {
            "id": 18,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/active_model/serializer/adapter.rb:23:in `as_json'"
          },
          {
            "id": 20,
            "trace": "bundle/ruby/2.2.0/bundler/gems/active_model_serializers-1577969cb763/lib/action_controller/serialization.rb:49:in `block (2 levels) in <module:Serialization>'"
          },
          {
            "id": 21,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/renderers.rb:45:in `block in _render_to_body_with_renderer'"
          },
          {
            "id": 22,
            "trace": "/Users/bfleischer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each_key'"
          },
          {
            "id": 23,
            "trace": "/Users/bfleischer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/set.rb:283:in `each'"
          },
          {
            "id": 24,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/renderers.rb:41:in `_render_to_body_with_renderer'"
          },
          {
            "id": 25,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'"
          },
          {
            "id": 26,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/rendering.rb:25:in `render'"
          },
          {
            "id": 27,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:16:in `render'"
          },
          {
            "id": 28,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'"
          },
          {
            "id": 29,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'"
          },
          {
            "id": 30,
            "trace": "/Users/bfleischer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'"
          },
          {
            "id": 31,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'"
          },
          {
            "id": 32,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'"
          },
          {
            "id": 33,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'"
          },
          {
            "id": 34,
            "trace": "bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'"
          },
          {
            "id": 35,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:43:in `render'"
          },
          {
            "id": 36,
            "trace": "app/controllers/items_controller.rb:309:in `show'"
          },
          {
            "id": 38,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'"
          },
          {
            "id": 39,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'"
          },
          {
            "id": 40,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'"
          },
          {
            "id": 41,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'"
          },
          {
            "id": 42,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'"
          },
          {
            "id": 43,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'"
          },
          {
            "id": 44,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'"
          },
          {
            "id": 45,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'"
          },
          {
            "id": 46,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'"
          },
          {
            "id": 47,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'"
          },
          {
            "id": 48,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'"
          },
          {
            "id": 49,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'"
          },
          {
            "id": 50,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'"
          },
          {
            "id": 51,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'"
          },
          {
            "id": 52,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'"
          },
          {
            "id": 54,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'"
          },
          {
            "id": 56,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'"
          },
          {
            "id": 57,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'"
          },
          {
            "id": 58,
            "trace": "bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'"
          },
          {
            "id": 59,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'"
          },
          {
            "id": 60,
            "trace": "bundle/ruby/2.2.0/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'"
          },
          {
            "id": 61,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:196:in `dispatch'"
          },
          {
            "id": 62,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'"
          },
          {
            "id": 63,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_controller/metal.rb:237:in `block in action'"
          },
          {
            "id": 64,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `call'"
          },
          {
            "id": 65,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'"
          },
          {
            "id": 66,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'"
          },
          {
            "id": 67,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'"
          },
          {
            "id": 68,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `each'"
          },
          {
            "id": 69,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/journey/router.rb:30:in `serve'"
          },
          {
            "id": 70,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:819:in `call'"
          },
          {
            "id": 71,
            "trace": "bundle/ruby/2.2.0/gems/bullet-4.14.0/lib/bullet/rack.rb:12:in `call'"
          },
          {
            "id": 72,
            "trace": "bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/etag.rb:24:in `call'"
          },
          {
            "id": 73,
            "trace": "bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/conditionalget.rb:25:in `call'"
          },
          {
            "id": 74,
            "trace": "bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'"
          },
          {
            "id": 75,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'"
          },
          {
            "id": 76,
            "trace": "bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/query_cache.rb:36:in `call'"
          },
          {
            "id": 77,
            "trace": "bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'"
          },
          {
            "id": 78,
            "trace": "bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/migration.rb:378:in `call'"
          },
          {
            "id": 79,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'"
          },
          {
            "id": 80,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'"
          },
          {
            "id": 81,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'"
          },
          {
            "id": 82,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_call_callbacks'"
          },
          {
            "id": 83,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'"
          },
          {
            "id": 84,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'"
          },
          {
            "id": 85,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/reloader.rb:73:in `call'"
          },
          {
            "id": 86,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'"
          },
          {
            "id": 87,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'"
          },
          {
            "id": 88,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'"
          },
          {
            "id": 89,
            "trace": "bundle/ruby/2.2.0/gems/logster-0.8.0/lib/logster/middleware/reporter.rb:31:in `call'"
          },
          {
            "id": 90,
            "trace": "bundle/ruby/2.2.0/gems/lograge-0.3.0/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'"
          },
          {
            "id": 91,
            "trace": "bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:22:in `call'"
          },
          {
            "id": 92,
            "trace": "bundle/ruby/2.2.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8:in `call'"
          },
          {
            "id": 93,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'"
          },
          {
            "id": 94,
            "trace": "bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call'"
          },
          {
            "id": 95,
            "trace": "bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"
          },
          {
            "id": 96,
            "trace": "bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/lock.rb:17:in `call'"
          },
          {
            "id": 97,
            "trace": "bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/static.rb:113:in `call'"
          },
          {
            "id": 98,
            "trace": "bundle/ruby/2.2.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'"
          },
          {
            "id": 99,
            "trace": "bundle/ruby/2.2.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'"
          },
          {
            "id": 100,
            "trace": "bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'"
          },
          {
            "id": 101,
            "trace": "bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'"
          },
```

also, ref: 
- https://github.com/rails-api/active_model_serializers/issues/882
- https://github.com/rails-api/active_model_serializers/issues/877

**Comment by edwardloveall** [comment]
I think I've narrowed it down to af81a40. I'm going to try and take this on but it might take me a bit to get in an figure it out. Happy to pair with someone also if they're into that.

**Comment by bf4** [comment]
I'd love to pair http://benjaminfleischer.com/pair
