### ISSUE TITLE
has_many :options doesn't work

### ISSUE THREAD

**Issue by klautcomputing** [rails-api/active_model_serializers#963]
I am in the process of updating to 0.10.0.rc2 and I have an Option model when I try to serialize it with:
```ruby
has_many :options
```
I get the error: 
```no implicit conversion of Symbol into Integer```.

If I rename the association via: 
```ruby 
has_many :foos, foreign_key: 'this_record_id', class_name: 'Option'
```
it works fine. 
BTW: I am upgrading from 0.9.3, hope that helps.

**Comment by Mexxerio** [comment]
Can confirm this issue.

I worked around it by renaming the association like you did and add an alias method
```ruby
def options
  self.foos
end
```

It would be awesome if that could be fixed though.

**Comment by bf4** [comment]
To clarify the code we're talking about, is this about right?

```ruby
class User < ActiveRecord::Base
  has_many :options
end
class UserSerializer < ActiveModel::Serializer
  has_many :options
end
class OptionsSerializer < ActiveModel::Serializer
end
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    render json: @user #=> no implicit conversion of Symbol into Integer.
  end
end
```

(options might not be a good table name. nor params, tasks, cases, classes, etc... :)

**Comment by klautcomputing** [comment]
Yes, seems about right. 
Well, it worked with 0.9.3. I guess because it was called serialization_options instead of options.
This is my current and ugly workaround
```ruby
class UserSerializer
  attributes :options
  def options
    o_serializer = ArraySerializer.new(object.options, each_serializer: OptionSerializer)
    ActiveModel::Serializer::Adapter::Json.new(o_serializer).serializable_hash
  end
end
```
is there a particular reason for calling it options instead of serialization_options?

**Comment by cornerman** [comment]
Please rename this back to serialization_options, as I think the name is too generic to be in scope (or is there a specific reason?). It might also be a good idea, to prefix the other ones as well, like: serialization_params/serialization_ tasks/...

**Comment by klautcomputing** [comment]
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux] and Rails 4.2.1 and I am running my rspec test which just does a get to show. If there is anything else I can help with just say so! Stripped my home path to make it a bit smaller.
```
TypeError:
no implicit conversion of Symbol into Integer
# ~/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:132:in `fetch'
# ~/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:132:in `public_send'
# ~/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:132:in `method_missing'
# ~/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:99:in `method_missing'
# ~/.rvm/gems/ruby-2.2.2/gems/active_model_serializers-0.10.0.rc2/lib/active_model/serializer/array_serializer.rb:12:in `block in initialize'
# ~/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `map'
# ~/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `map'
# ~/.rvm/gems/ruby-2.2.2/gems/active_model_serializers-0.10.0.rc2/lib/active_model/serializer/array_serializer.rb:11:in `initialize'
# ~/.rvm/gems/ruby-2.2.2/gems/active_model_serializers-0.10.0.rc2/lib/active_model/serializer.rb:209:in `new'
# ~/.rvm/gems/ruby-2.2.2/gems/active_model_serializers-0.10.0.rc2/lib/active_model/serializer.rb:209:in `block in each_association'
# ~/.rvm/gems/ruby-2.2.2/gems/active_model_serializers-0.10.0.rc2/lib/active_model/serializer.rb:202:in `each'
# ~/.rvm/gems/ruby-2.2.2/gems/active_model_serializers-0.10.0.rc2/lib/active_model/serializer.rb:202:in `each_association'
# ~/.rvm/gems/ruby-2.2.2/gems/active_model_serializers-0.10.0.rc2/lib/active_model/serializer/adapter/json.rb:17:in `serializable_hash'
# ~/.rvm/gems/ruby-2.2.2/gems/active_model_serializers-0.10.0.rc2/lib/active_model/serializer/adapter/flatten_json.rb:6:in `serializable_hash'
# ~/.rvm/gems/ruby-2.2.2/gems/active_model_serializers-0.10.0.rc2/lib/active_model/serializer/adapter.rb:24:in `as_json'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/json/encoding.rb:34:in `encode'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/json/encoding.rb:21:in `encode'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/renderers.rb:116:in `block in <module:Renderers>'
# ~/.rvm/gems/ruby-2.2.2/gems/active_model_serializers-0.10.0.rc2/lib/action_controller/serialization.rb:49:in `block (2 levels) in <module:Serialization>'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/renderers.rb:45:in `block in _render_to_body_with_renderer'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/renderers.rb:41:in `_render_to_body_with_renderer'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/abstract_controller/rendering.rb:25:in `render'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:16:in `render'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
# ~/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
# ./app/controllers/api/users_controller.rb:9:in `show'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:198:in `process_action'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:117:in `call'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:505:in `call'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:92:in `_run_callbacks'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
# ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
# ~/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/abstract_controller/base.rb:137:in `process'
# ~/.rvm/gems/ruby-2.2.2/gems/actionview-4.2.1/lib/action_view/rendering.rb:30:in `process'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/test_case.rb:632:in `process'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/test_case.rb:65:in `process'
# ~/.rvm/gems/ruby-2.2.2/gems/devise-3.4.1/lib/devise/test_helpers.rb:19:in `block in process'
# ~/.rvm/gems/ruby-2.2.2/gems/devise-3.4.1/lib/devise/test_helpers.rb:72:in `catch'
# ~/.rvm/gems/ruby-2.2.2/gems/devise-3.4.1/lib/devise/test_helpers.rb:72:in `_catch_warden'
# ~/.rvm/gems/ruby-2.2.2/gems/devise-3.4.1/lib/devise/test_helpers.rb:19:in `process'
# ~/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.1/lib/action_controller/test_case.rb:508:in `get'
# ./spec/controllers/api/users_controller_spec.rb:24:in `block (3 levels) in <top (required)>'
# ./spec/rails_helper.rb:62:in `block (3 levels) in <top (required)>'
# ~/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.4.1/lib/database_cleaner/generic/base.rb:15:in `cleaning'
# ~/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.4.1/lib/database_cleaner/base.rb:92:in `cleaning'
# ~/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
# ~/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `call'
# ~/.rvm/gems/ruby-2.2.2/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
# ./spec/rails_helper.rb:61:in `block (2 levels) in <top (required)>'

```

**Comment by bf4** [comment]
Thanks.  This might be relevant to https://github.com/rails-api/active_model_serializers/pull/962

**Comment by beauby** [comment]
Closing for now, as I believe this is fixed in master (`options` has been renamed to `instance_options`). Feel free to reopen if needed.

**Comment by kulte** [comment]
You can also use the following if you are on 0.10.0.rc3 and can't upgrade to master:

```
has_many :opts, key: 'options'

[...]

def opts
  object.options
end
```
